# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for installing Workstation in Linux or Windows machine.
#
- name: install_workstation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test case is blocked"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Required parameter 'workstation_download_url' is not defined to be a valid value: '{{ workstation_download_url | default('') }}'"
            skip_reason: "Blocked"
          when:
            - workstation_download_url is undefined or not workstation_download_url

        - name: "Initialize Desktop Hypervisor install status and installed path"
          ansible.builtin.set_fact:
            dh_host_installed: false
            dh_host_installed_path: ''
        - name: "Test setup"
          include_tasks: ../common/dh_test_setup.yml
          vars:
            create_dh_test_folder: true

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to VMware Workstation is supported to be installed on 64bit OS, this host machine OS is: {{ guest_os_ansible_architecture | default('') }}."
            skip_reason: "Not Supported"
          when:
            - guest_os_ansible_architecture is defined
            - guest_os_ansible_architecture != "64-bit"

        - name: "Set fact of current test case name"
          ansible.builtin.set_fact:
            current_testcase_name: "install_workstation_in_{{ host_machine_type }}_host"
        - name: "Set fact of current test case name"
          ansible.builtin.set_fact:
            current_testcase_name: "{{ current_testcase_name ~ '_vm' }}" 
          when: is_vsphere_env

        - name: "Check Workstation install status in Windows host"
          include_tasks: ../../windows/utils/win_get_software_install_status.yml
          vars:
            win_software_name: "VMware Workstation"
            vm_guest_ip: "{{ host_machine_hostname }}"
        - name: "Set fact of Workstation install status"
          ansible.builtin.set_fact:
            dh_host_installed: "{{ win_software_is_installed }}"
        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Test case '{{ ansible_play_name }}' is skipped because Workstation is already installed, while 'update_workstation' is set to: {{ update_workstation | default(false) }}"
            skip_reason: "Skipped"
          when:
            - update_workstation is undefined or not update_workstation
            - dh_host_installed

        - name: "Enable host VM nested virtualization"
          include_tasks: enable_host_vm_nested_virtual.yml
          when: is_vsphere_env

        - name: "Get host VM VBS status"
          include_tasks: ../../windows/utils/win_get_vbs_guest.yml
          vars:
            vm_guest_ip: "{{ host_machine_hostname }}"
          when:
            - not is_vsphere_env
            - guest_os_ansible_distribution_major_ver | int == 10 and guest_os_build_num | int >= 14393

        - name: "Check host VM nested virtualization"
          block:
            - name: "Get if host require nested virtualization"
              include_tasks: check_host_vm_nested_virtual.yml
            - name: "Skip test case"
              include_tasks: ../../common/skip_test_case.yml
              vars:
                skip_msg: "Test case '{{ ansible_play_name }}' is blocked because host machine is a virtual machine while VM nested virtualization is not enabled."
                skip_reason: "Blocked"
              when:
                - dh_host_is_vm
                - not dh_host_nest_virtual
          when:
            - not is_vsphere_env
            - win_vbs_status_guest is defined
            - not (win_vbs_status_guest | int == 1 or win_vbs_status_guest | int == 2)
            # win_vbs_status_guest =
            #    0. VBS is not enabled.
            #    1. VBS is enabled but not running.
            #    2. VBS is enabled and running.

        - name: "Install Workstation in Windows host"
          block:
            # - name: "Uninstall Workstation firstly"
            # include_tasks: TBD.yml
            # when:
            # - win_software_is_installed
            # - update_workstation is defined and update_workstation
            - name: "Install Workstation"
              include_tasks: install_ws_windows_host.yml
          when: host_machine_type == "windows"

        # - name: "Install Workstation in Linux host"
        #   include_tasks: TBD
        #   when: host_machine_type == "linux"

        - name: "Diskplay Desktop Hypervisor status"
          ansible.builtin.debug:
            msg:
              - "Desktop Hypervisor is installed: {{ dh_host_installed }}"
              - "Desktop Hypervisor is installed to : {{ dh_host_installed_path }}"
        - name: "Reset base snapshot"
          include_tasks: ../../common/reset_base_snapshot.yml
          when: is_vsphere_env
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
          vars:
            exit_testing_when_fail: true
          when: is_vsphere_env
