# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Set timestamp of failure state"
  ansible.builtin.set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"

- name: "Print failed test case"
  ansible.builtin.debug:
    msg: "Testcase: {{ current_testcase_name }} failed"

- name: "Check if current test case log folder exists"
  ansible.builtin.stat:
    path: "{{ current_test_log_folder }}"
  register: current_test_folder_result
  ignore_errors: true

- name: "Create current test case log folder"
  include_tasks: ../../common/create_directory.yml
  vars:
    dir_path: "{{ current_test_log_folder }}"
    dir_mode: "0777"
  when: not current_test_folder_result.stat.exists

- name: "Collect VM's information"
  block:
    # - name: "Take a screenshot at VM current state"
    # - name: "Download VM's vmware.log"
    - name: "Take a snapshot at VM current state"
      include_tasks: win_host_take_vm_snapshot.yml
      vars:
        take_snapshot_name: "{{ current_testcase_name }}_fail_{{ timestamp }}"
  when:
    - dh_vm_exists is defined
    - dh_vm_exists | bool

- name: "Testing exit due to failure"
  ansible.builtin.fail:
    msg: "Exit testing because 'exit_testing_when_fail' is set to {{ exit_testing_when_fail }} in test case {{ current_testcase_name }}"
  when:
    - exit_testing_when_fail is defined
    - exit_testing_when_fail | bool
