# Copyright 2025 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Set fact of the condidtions of the known issue on Windows 11"
  ansible.builtin.set_fact:
    win11_known_issue: "{{ os_fullname_guest is search('Windows 11') and esxi_version is version('7.0.3', '=') and esxi_build == '19193900' and vmtools_version is version('12.0.0', '>=') }}"

- name: "Known issue - incorrect/empty guestID in guest info of Windows 11"
  ansible.builtin.debug:
    msg:
      - "The guestID of Windows 11 guest in guestinfo is empty on ESXi 7.0U3c. Ignore this known issue."
      - "Please refer to https://knowledge.broadcom.com/external/article?legacyId=86517."
  tags:
    - known_issue
  when:
    - win11_known_issue
    - not guestinfo_guest_id

- name: "Check guest ID got from guest info is not empty"
  ansible.builtin.assert:
    that:
      - guestinfo_guest_id
    fail_msg: "Guest ID in guest info is '{{ guestinfo_guest_id }}', which should be a valid value firstly."
  when: not win11_known_issue
