# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Set fact of the dict of the Windows guest OS info"
  ansible.builtin.set_fact:
    win_gos_info: [
      'Windows 10 32bit': {
        'win_guest_id': 'windows9Guest',
        'win_guest_vmtools': '10.0.0',
        'win_guest_creation_esxi': 'NA',
        'win_guest_fullname': 'Microsoft Windows 10 (32-bit)'
      },
      'Windows 10 64bit': {
        'win_guest_id': 'windows9_64Guest',
        'win_guest_vmtools': '10.0.0',
        'win_guest_creation_esxi': 'NA',
        'win_guest_fullname': 'Microsoft Windows 10 (64-bit)'
      },
      'Windows 11': {
        'win_guest_id': 'windows11_64Guest',
        'win_guest_vmtools': '12.0.0',
        'win_guest_creation_esxi': 'NA',
        'win_guest_fullname': 'Microsoft Windows 11 (64-bit)'
      },
      'Windows next': {
        'win_guest_id': 'NA',
        'win_guest_vmtools': 'NA',
        'win_guest_creation_esxi': 'NA',
        'win_guest_fullname': 'NA'
      },
      'Windows Server 2016': {
        'win_guest_id': 'windows9Server64Guest',
        'win_guest_vmtools': '10.0.0',
        'win_guest_creation_esxi': 'NA',
        'win_guest_fullname': 'Microsoft Windows Server 2016 (64-bit)'
      },
      'Windows Server 2019': {
        'win_guest_id': 'windows2019srv_64Guest',
        'win_guest_vmtools': 'NA',
        'win_guest_creation_esxi': '7.0.0',
        'win_guest_fullname': 'Microsoft Windows Server 2019 (64-bit)'
      },
      'Windows Server 2022': {
        'win_guest_id': 'Windows2019srvNext_64Guest',
        'win_guest_vmtools': '11.3.0',
        'win_guest_creation_esxi': '',
        'win_guest_fullname': 'Microsoft Windows Server 2022 (64-bit)'
      },
      'Windows Server 2025': {
        'win_guest_id': 'Windows2022srvNext_64Guest',
        'win_guest_vmtools': '12.0.5',
        'win_guest_add_esxi': '8.0.0',
        'win_guest_creation_esxi': '8.0.3',
        'win_guest_fullname': 'Microsoft Windows Server 2025 (64-bit)'
      },
      'Windows Server next': {
        'win_guest_id': 'NA',
        'win_guest_vmtools': 'NA',
        'win_guest_creation_esxi': 'NA',
        'win_guest_fullname': 'NA'
      }
    ]
