# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for checking quiesce snapshot taken
# on VM through VMware Tools. If VMware Tools is not installed
# or not running in guest OS, this test case result is 'Blocked'.
#
- name: check_quiesce_snapshot
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            skip_test_no_vmtools: true

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              Skip test case '{{ ansible_play_name }}' because 'vmvss' service is not available in the guest OS
              on ESXi on ARM, the installed services and their status are '{{ vmtools_service_dict }}'.
            skip_reason: "Not Supported"
          when:
            - esxi_cpu_vendor == 'arm'
            - "'vmvss' not in vmtools_service_dict.keys()"

        - name: "Check 'vmvss' service"
          ansible.builtin.assert:
            that:
              - vmtools_service_dict.keys() | length != 0
              - 'vmvss' in vmtools_service_dict.keys()
            fail_msg: >-
              'vmvss' service is required but not found in the VMware Tools services dict got in
              guest OS '{{ vmtools_service_dict }}'.
          when: esxi_cpu_vendor != 'arm'

        - name: "Check disk.EnableUUID in VMX file for Windows Server"
          include_tasks: check_vmx_disk_enable_uuid.yml
          when: guest_os_product_type == "server"

        - name: "Preparation for this test case"
          include_tasks: prepare_quiesce_snapshot.yml

        - name: "Take quiesce snapshot of VM"
          include_tasks: ../../common/vm_take_snapshot.yml
          vars:
            snapshot_name: "{{ quiesce_snapshot_name }}"
            is_quiesce: true
            dump_memory: false

        - name: "Check custom scripts executed"
          include_tasks: check_custom_scripts_executed.yml

        - name: "Check quiescing type"
          include_tasks: check_quiescing_type.yml

        - name: "Remove quiesce snapshot at test success"
          include_tasks: ../../common/vm_remove_snapshot.yml
          vars:
            snapshot_name: "{{ quiesce_snapshot_name }}"
      rescue:
        - name: "Collect vss logs"
          include_tasks: collect_vss_logs.yml
          when: collect_vss_logs is defined and collect_vss_logs

        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
