# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for check hotadd and hot remove e1000e
# network adapter to VM.
#
- name: e1000e_network_device_ops
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Set fact of the network adapter type"
      ansible.builtin.set_fact:
        nic_type: 'E1000E'

    - name: "Test case block"
      block:
        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              Skip test case '{{ ansible_play_name }}' because E1000E network adapter is not supported
              on ESXi on ARM.
            skip_reason: "Not Supported"
          when: esxi_cpu_vendor == 'arm'

        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml

        - name: "Add new {{ nic_type }} network adapter to VM and verify status"
          include_tasks: network_adapter_deviceops.yml
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
