# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Prepare network environment for new network adapter"
  include_tasks: ../../common/network_testbed_setup.yml

- name: "Get network adapter number before hot add"
  include_tasks: network_adapter_number_check.yml

- name: "Set fact of network adapter info before hot add"
  ansible.builtin.set_fact:
    nic_num_before_hotadd: "{{ vm_nic_num_get }}"
    nic_mac_addr_list_before_hotadd: "{{ vm_nic_mac_addr_list_get }}"
    nic_num_before_hotadd_guest: "{{ guest_nic_num_get }}"

- name: "Hot add a new network adapter to VM"
  include_tasks: ../../common/vm_add_network_adapter.yml
  vars:
    adapter_type: "{{ nic_type | lower }}"
    vm_portgroup_name: "{{ network_env_net_name }}"

- name: "Check new network adapter hot add operation"
  ansible.builtin.assert:
    that:
      - add_adapter.changed
    fail_msg: "The result of hot adding VM network adapter task is not changed."

- name: "Wait 10 seconds after network adapter hot added"
  ansible.builtin.pause:
    seconds: 10

- name: "Get network adapter number after hot add"
  include_tasks: network_adapter_number_check.yml

- name: "Set fact of network adapter info after hot add"
  ansible.builtin.set_fact:
    nic_num_after_hotadd: "{{ vm_nic_num_get }}"
    nic_mac_addr_list_after_hotadd: "{{ vm_nic_mac_addr_list_get }}"
    nic_num_after_hotadd_guest: "{{ guest_nic_num_get }}"

- name: "Set fact of MAC address of new added network adapter"
  ansible.builtin.set_fact:
    new_nic_mac_address: "{{ (nic_mac_addr_list_after_hotadd | difference(nic_mac_addr_list_before_hotadd))[0] | default('') }}"

- name: "Get IP address of new added network adapter"
  include_tasks: get_network_adapter_ip.yml

- name: "Disconnection and reconnection test"
  include_tasks: network_adapter_status_check.yml

- name: "Remove new added network adapter"
  include_tasks: ../../common/vm_remove_network_adapter.yml
  vars:
    netadapter_mac_addr: "{{ new_nic_mac_address }}"

- name: "Check network adapter remove operation"
  ansible.builtin.assert:
    that:
      - remove_adapter.changed
    fail_msg: "The result of hot removing VM network adapter task is not changed."

- name: "Wait 10 seconds after network adapter hot remove"
  ansible.builtin.pause:
    seconds: 10

- name: "Get the number of VM network adapter after hot remove"
  include_tasks: network_adapter_number_check.yml

- name: "Set fact of network adapter info after hot remove"
  ansible.builtin.set_fact:
    nic_num_after_hotremove: "{{ vm_nic_num_get }}"
    nic_num_after_hotremove_guest: "{{ guest_nic_num_get }}"

- name: "Display test results of '{{ nic_type }}' in check conditions"
  ansible.builtin.debug:
    msg:
      - "New network adapter MAC address: {{ new_nic_mac_address }}"
      - "Network adapter number on VM before hot add: {{ nic_num_before_hotadd }}"
      - "Network adapter number on VM after hot add: {{ nic_num_after_hotadd }}"
      - "Network adapter number in guest before hot add: {{ nic_num_before_hotadd_guest }}"
      - "Network adapter number in guest after hot add: {{ nic_num_after_hotadd_guest }}"
      - "Network adapter number on VM after hot remove: {{ nic_num_after_hotremove }}"
      - "Network adapter number in guest after hot remove: {{ nic_num_after_hotremove_guest }}"
      - "Ping network gateway result after hot add: {{ ping_result_after_hotadd }}"
      - "Ping network gateway result after disable in guest: {{ ping_result_after_disable }}"
      - "Ping network gateway result after re-enable in guest: {{ ping_result_after_enable }}"
      - "Ping network gateway result after disconnect from VM: {{ ping_result_after_disconnect }}"
      - "Ping network gateway result after re-connect from VM: {{ ping_result_after_reconnect }}"

- name: "Verify the number of network adapter and network connection status"
  ansible.builtin.assert:
    that:
      - new_nic_mac_address | ansible.utils.hwaddr
      - nic_num_before_hotadd | int == nic_num_before_hotadd_guest | int
      - nic_num_after_hotadd | int == nic_num_after_hotadd_guest | int
      - nic_num_before_hotadd | int == nic_num_after_hotadd | int - 1
      - nic_num_after_hotadd_guest | int == nic_num_before_hotadd_guest | int + 1
      - nic_num_after_hotremove | int == nic_num_before_hotadd | int
      - nic_num_after_hotremove_guest | int == nic_num_before_hotadd_guest | int
      - ping_result_after_hotadd
      - not ping_result_after_disable
      - ping_result_after_enable
      - not ping_result_after_disconnect
      - ping_result_after_reconnect
    fail_msg: "One or more check conditions failed, please check above displayed results."
