# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Refer to this doc: https://learn.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys
- name: "Set fact of the dict of Windows versions and KMS client setup keys"
  ansible.builtin.set_fact:
    win_kms_client_setup_key:
      "Microsoft Windows 10 Enterprise": "NPPR9-FWDCX-D2C8J-H872K-2YT43"
      "Microsoft Windows Server 2022 Datacenter": "WX4NM-KYWYW-QJJR4-XV3QB-6VM33"

# Refer to this doc: https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-command-line-options?view=windows-11
- name: "Set fact of the command of Windows upgrade"
  ansible.builtin.set_fact:
    win_upgrade_setup_cmd: "{{ upgrade_to_iso_drive }}:\\setup.exe /auto upgrade /quiet /eula accept /compat scanonly /compat /ignorewarning /copylogs C:\\upgrade.log /dynamicupdate disable /MigNEO disable /NoReboot"
