# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Set Windows edition to upgrade to corresponding edition
- name: "Initialize the fact of Windows edition"
  ansible.builtin.set_fact:
    win_guest_edition: "Enterprise"
- include_tasks: ../utils/get_windows_system_info.yml
  when: not guest_os_ansible_distribution
- name: "Set fact of Windows edition"
  ansible.builtin.set_fact:
    win_guest_edition: "{{ guest_os_ansible_distribution.split(' ')[-1] }}"
  when: guest_os_ansible_distribution

# Get if VM with PVSCSI and VMXNET3 devices before OS upgrading
- include_tasks: get_pvscsi_vmxnet3_info.yml

# VM connect to upgrade ISO image
- include_tasks: mount_upgrade_to_iso.yml

# Do in-place upgrade in guest OS
# Check OS upgrade
# Check VMware Tools
# Check pvscsi or vmxnet3 devices
# Uninstall VMware Tools
# Reinstall VMware Tools
