# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Initialize CPU hot add number list"
  ansible.builtin.set_fact:
    cpu_hotadd_num_list: []

- name: "Get ESXi host logical processor number"
  include_tasks: ../../common/esxi_get_cpu_mem_info.yml

# Set the maximum VM vCPU number set in this test to the
# minimum of ESXi host logical processor number and the
# configured parameter 'vm_cpu_hotadd_max' (default 16)
# in vars/test.yml.
- name: "Set fact of the maximum vCPU number of hot add test"
  ansible.builtin.set_fact:
    max_num_cpus: "{{ [esxi_logical_cpu_num | int, vm_cpu_hotadd_max | default(16) | int] | min }}"
- name: "Maximum VM vCPU number of CPU hot add test"
  ansible.builtin.debug: var=max_num_cpus

# Assume hot added vCPU number is 1, 2, 3, ..., etc. in each test loop,
# and after hot add, VM vCPU number is less than the value of 'max_num_cpus'.
# Assume will do N times CPU hot add,
# 1 + 2 + 3 + ... + N = max_num_cpus - initial_cpu_num,
# we set N = root((max_num_cpus - initial_cpu_num) * 2) here for convenience.
- name: "Set fact of the vCPU number increase list"
  ansible.builtin.set_fact:
    cpu_hotadd_num_list: "{{ range(1, (((max_num_cpus | int - initial_cpu_num | int) * 2) | root | int)) | list }}"
- name: "Display the vCPU number increase list"
  ansible.builtin.debug: var=cpu_hotadd_num_list
