# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
#
- name: "Get guest OS version build"
  include_tasks: ../utils/win_get_os_version.yml
- name: "Display the guest OS version build before online Windows Updates"
  ansible.builtin.debug:
    msg: "Before running online Windows Updates, guest OS version build is {{ win_os_version_build }}"

- name: "Set the online Windows Updates reject list"
  ansible.builtin.set_fact:
    win_updates_reject_list: "{{ windows_updates_reject_list.split(',') | map('trim') }}"
  when:
    - windows_updates_reject_list is defined
    - windows_updates_reject_list

- name: "Install online Windows Updates"
  include_tasks: ../utils/win_install_online_updates.yml
  vars:
    win_updates_ignore_errors: true

- name: "Check if online Windows Updates log file exists in guest OS"
  include_tasks: ../utils/win_check_file_exist.yml
  vars:
    win_check_file_exist_file: "{{ win_updates_log_file }}"

- name: "Fetch the online Windows Updates log file to local machine and delete it from guest OS"
  when: win_check_file_exist_result
  block:
    - name: "Get online Windows Updates log file from guest OS to local machine"
      include_tasks: ../utils/win_get_file.yml
      vars:
        win_get_file_src_path: "{{ win_updates_log_file }}"
        win_get_file_dst_path: "{{ current_test_log_folder }}"

    - name: "Delete online Windows Updates log file from guest OS"
      ansible.windows.win_file:
        path: "{{ win_updates_log_file }}"
        state: absent
      delegate_to: "{{ vm_guest_ip }}"
      register: delete_file_result
      ignore_errors: true

# For internal existing VM test scenario.
# If guest OS has been updated, take a new one as base snapshot and remove the old one.
- name: "Reset base snapshot if online Windows Updates succeeds"
  when: win_online_updates_succeed | bool
  block:
    - name: "Get guest OS version build"
      include_tasks: ../utils/win_get_os_version.yml
    - name: "Display the guest OS version build after online Windows Updates"
      ansible.builtin.debug:
        msg: "After running online Windows Updates, guest OS version build is {{ win_os_version_build }}"

    - name: "Reset the base snapshot and remove the old one"
      include_tasks: ../../common/reset_base_snapshot.yml
      vars:
        remove_old_base_snapshot: true
        base_snapshot_description: "{{ win_os_version_build }}"

- name: "Revert to the base snapshot when online Windows Updates failed"
  include_tasks: ../../common/base_snapshot_check_revert.yml
  when: not win_online_updates_succeed | bool
