# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Set fact of the valid SCSI controller types list"
  ansible.builtin.set_fact:
    valid_scsi_controller_list: ['buslogic', 'paravirtual', 'lsilogicsas', 'lsilogic']

- name: "Set disk controller type to scsi, sata or nvme"
  ansible.builtin.set_fact:
    disk_controller: "{{ 'scsi' if test_disk_controller_type in valid_scsi_controller_list else test_disk_controller_type }}"

- name: "Get VM disk controllers info"
  include_tasks: ../../common/vm_get_disk_controller_facts.yml

- name: "Set fact of VM disk controllers before testing"
  ansible.builtin.set_fact:
    disk_controllers_before_hotadd: "{{ disk_controller_facts['disk_controller_data'] }}"

- name: "Print VM disk controllers before testing"
  ansible.builtin.debug: var=disk_controllers_before_hotadd

- name: "Set fact of the number of '{{ disk_controller }}' controller"
  ansible.builtin.set_fact:
    disk_controller_count: "{{ disk_controllers_before_hotadd[disk_controller] | default({}) | length }}"
