# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# This task is used for getting existing disk controller number
# and new disk controller bus number
#
- name: "Set fact of the valid SCSI controller types list"
  ansible.builtin.set_fact:
    valid_scsi_controller_list: ['buslogic', 'paravirtual', 'lsilogicsas', 'lsilogic']

- name: "Set disk controller type to scsi, sata or nvme"
  ansible.builtin.set_fact:
    disk_controller: "{{ 'scsi' if test_disk_controller_type in valid_scsi_controller_list else test_disk_controller_type }}"

- name: "Get the total number of controllers with type: scsi, sata or nvme"
  include_tasks: ../../common/vm_get_disk_controller_num.yml

- name: "Set controller '{{ disk_controller }}' number before hotadd"
  ansible.builtin.set_fact:
    vhba_number_before_hotadd: "{{ vhba_number }}"

# New disk controller can be added when existing controller number < 4
- name: "Set fact of run add new disk controller test when it's number < 4"
  ansible.builtin.set_fact:
    add_new_controller: "{{ vhba_number_before_hotadd | int < 4 }}"

# Get new disk controller bus number
- include_tasks: ../../common/vm_get_new_vhba_bus_number.yml
  vars:
    disk_controller_facts_data: "{{ disk_controller_facts.disk_controller_data }}"
    new_vhba_type: "{{ disk_controller }}"
  when: add_new_controller

- name: "Print the existing and new controller info"
  ansible.builtin.debug:
    msg:
      - "The under test disk controller type: {{ disk_controller }}"
      - "The number of under test disk controller before hotadd: {{ vhba_number_before_hotadd }}"
      - "Add new under test disk controller: {{ add_new_controller }}"
      - "New under test disk controller bus number is got: {{ new_vhba_bus_found }}"
