# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Handle known issue"
  block:
    - name: "Known issue - VM boot order changed after hot adding disk to new SATA controller"
      ansible.builtin.debug:
        msg:
          - "The boot order of VM with BIOS firmware and without IDE/SATA boot disk controller may be changed after hot adding new disk to the new SATA controller."
          - "VM can not boot up due to this known issue."
          - "Setting VM boot disk explicitly in boot order is the workaround."
      tags:
        - known_issue

    - name: "Set boot disk"
      include_tasks: ../../common/vm_set_boot_options.yml
      vars:
        boot_hdd_name: "{{ boot_disk_label }}"
        boot_order_list:
          - disk
