# Copyright 2025 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---    
- name: "Known issue - hot extended NVMe disk size is not recognized"
  ansible.builtin.debug:
    msg:
      - "Hot extended NVMe disk size is not recognized in Windows guest OS when NVMe Spec v1.3 is emulated."
      - "Ignore this known issue on ESXi version < 8.0 Update 1 build 21495797."
      - "Restart guest OS is the workaround for this hot extending NVMe disk issue."
  tags:
    - known_issue

- name: "Restart guest OS"
  include_tasks: ../utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "restart"
