# Copyright 2022-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Hot add a new disk controller and disk with 1GB by default"
  include_tasks: hotadd_disk_new_ctrl.yml

- name: "Get disk volume size in guest OS before hot extend"
  include_tasks: ../utils/win_get_disk_volume_size.yml
  vars:
    win_disk_volume_letter: "{{ drive_letter_new }}"

- name: "Set fact of the disk volume size before hot extend"
  ansible.builtin.set_fact:
    win_disk_volume_size_before: "{{ win_get_volume_size_gb }}"

- name: "Check disk volume size before hot extend"
  ansible.builtin.assert:
    that:
      - win_disk_volume_size_before | int == 1
    fail_msg: "Got disk volume '{{ drive_letter_new }}' size '{{ win_disk_volume_size_before }}' GB before extend, not 1GB."

- name: "Hot extend the VM disk size to 2GB"
  include_tasks: ../../common/vm_hot_add_remove_disk.yml
  vars:
    disk_operation: 'present'
    disk_controller_type: "{{ test_disk_ctrl_type }}"
    ctrl_number: "{{ new_vhba_bus_number }}"
    unit_number: 0
    disk_size_gb: 2

- name: "Wait 10 seconds after disk hot extend"
  ansible.builtin.pause:
    seconds: 10

- name: "Get disk size in guest OS after hot extend"
  include_tasks: ../utils/win_get_disk_size.yml
  vars:
    win_disk_uid: "{{ win_disk_unique_id }}"

- name: "Set fact of disk size after extend"
  ansible.builtin.set_fact:
    win_disk_size_after: "{{ win_get_disk_size_gb }}"

- name: "Print disk size got in guest OS"
  ansible.builtin.debug:
    msg:
      - "Before disk hot extend, disk size in guest OS: {{ win_disk_volume_size_before }}GB"
      - "After disk hot extend, disk size in guest OS: {{ win_disk_size_after }}GB"

- name: "Handle known issue"
  when:
    - win_disk_size_after | int == win_disk_volume_size_before | int
    - esxi_version is version('8.0.1', '<=') and esxi_build != 'N/A' and esxi_build | int < 21495797
  block:
    - name: "Workaround for the known issue"
      include_tasks: handle_nvme_extend_known_issue.yml

    - name: "Get disk size again after guest OS restart"
      include_tasks: ../utils/win_get_disk_size.yml
      vars:
        win_disk_uid: "{{ win_disk_unique_id }}"

    - name: "Set fact of disk size after guest OS restart"
      ansible.builtin.set_fact:
        win_disk_size_after: "{{ win_get_disk_size_gb }}"

- name: "Check disk size after hot extend"
  ansible.builtin.assert:
    that:
      - win_disk_size_after | int == 2
    fail_msg: "Got disk size '{{ win_disk_size_after }}' GB in guest OS after hot extend, not 2GB."

- name: "Extend disk volume to the new size"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: "Resize-Partition -DriveLetter {{ drive_letter_new }} -Size (Get-PartitionSupportedSize -DriveLetter {{ drive_letter_new }}).SizeMax"

- name: "Get disk volume size in guest OS after extend"
  include_tasks: ../utils/win_get_disk_volume_size.yml
  vars:
    win_disk_volume_letter: "{{ drive_letter_new }}"

- name: "Set fact of the disk volume size after extend"
  ansible.builtin.set_fact:
    win_disk_volume_size_after: "{{ win_get_volume_size_gb }}"

- name: "Check disk volume size after extend"
  ansible.builtin.assert:
    that:
      - win_disk_volume_size_after | int == 2
    fail_msg: "Got disk volume '{{ drive_letter_new }}' size '{{ win_disk_volume_size_after }}' GB after extend, not 2GB."
