# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get disk number in guest OS before hot adding to existing controller"
  include_tasks: ../utils/win_get_disk_num.yml

- name: "Set fact of disk number before hot adding to existing controller"
  ansible.builtin.set_fact:
    disk_num_guest_before_hotadd: "{{ disk_num_guest }}"

- name: "Hot add a new disk to the existing {{ test_disk_controller_type if not test_on_boot_ctrl else 'boot' }} controller"
  include_tasks: ../../common/vm_hot_add_remove_disk.yml
  vars:
    disk_operation: 'present'
    disk_controller_type: "{{ test_disk_controller_type }}"
    ctrl_number: "{{ new_vhba_bus_number if not test_on_boot_ctrl else boot_disk_ctl_bus_num }}"
    unit_number: 1

- name: "Wait 15 seconds after disk hot add"
  ansible.builtin.pause:
    seconds: 15

- name: "Get disk number in guest OS after hot adding to existing controller"
  include_tasks: ../utils/win_get_disk_num.yml

- name: "Set fact of disk number after hot adding to existing controller"
  ansible.builtin.set_fact:
    disk_num_guest_after_hotadd: "{{ disk_num_guest }}"

- name: "Print the disk number in guest OS"
  ansible.builtin.debug:
    msg:
      - "Before hot add, the number of disk in guest: {{ disk_num_guest_before_hotadd }}"
      - "After hot add, the number of disk in guest: {{ disk_num_guest_before_hotadd }}"

- name: "Handle known issue"
  when:
    - disk_num_guest_after_hotadd | int != disk_num_guest_before_hotadd | int + 1
    - test_disk_controller_type == 'nvme'
    - test_purpose == "hot-add"
  block:
    - name: "Workaround for the known issue"
      include_tasks: handle_nvme_known_issue.yml
    - name: "Get disk number in guest OS after restart"
      include_tasks: ../utils/win_get_disk_num.yml
    - name: "Reset the fact of disk number after guest restart"
      ansible.builtin.set_fact:
        disk_num_guest_after_hotadd: "{{ disk_num_guest }}"

- name: "Verify disk number increases 1 in guest OS"
  ansible.builtin.assert:
    that:
      - disk_num_guest_after_hotadd | int == disk_num_guest_before_hotadd | int + 1
    fail_msg: >-
      Testing failed at hot adding new disk to the existing
      {{ test_disk_controller_type if not test_on_boot_ctrl else 'boot' }} controller. 
      Disk number before hot add: {{ disk_num_guest_before_hotadd }}, after hot add: {{ disk_num_guest_after_hotadd }}.

- name: "Initialize new disk and create disk partition in guest OS"
  include_tasks: create_partition_raw_disk.yml
  vars:
    on_new_controller: false

- name: "Remove the new added disk to boot disk controller"
  include_tasks: hotremove_disk_boot_ctrl.yml
