# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get disk controller and disk number in guest OS before hot adding new disk controller and disk"
  include_tasks: get_guest_disk_ctl_num.yml

- name: "Set fact of disk controller and disk number before hot adding new disk controller and disk"
  ansible.builtin.set_fact:
    ctl_num_guest_before_hotadd: "{{ ctl_num_guest }}"
    disk_num_guest_before_hotadd: "{{ disk_num_guest }}"

- name: "Hot add new disk controller and disk at the same time"
  include_tasks: ../../common/vm_hot_add_ctrl_disk.yml
  vars:
    disk_controller_type: "{{ test_disk_controller_type }}"
    ctrl_number: "{{ new_vhba_bus_number }}"
    unit_number: 0

- name: "Wait 10 seconds after new disk controller and disk hot add"
  ansible.builtin.pause:
    seconds: 10

- name: "Get disk controller and disk number in guest OS after hot adding new disk controller and disk"
  include_tasks: get_guest_disk_ctl_num.yml

- name: "Set fact of disk controller and disk number after hot adding new disk controller and disk"
  ansible.builtin.set_fact:
    ctl_num_guest_after_hotadd: "{{ ctl_num_guest }}"
    disk_num_guest_after_hotadd: "{{ disk_num_guest }}"

- name: "Print the disk controller and disk number in guest OS"
  ansible.builtin.debug:
    msg:
      - "Before hot adding, the number of '{{ disk_controller }}' controller: {{ ctl_num_guest_before_hotadd }}"
      - "After hot adding, the number of '{{ disk_controller }}' controller: {{ ctl_num_guest_after_hotadd }}"
      - "Before hot adding, the number of disk: {{ disk_num_guest_before_hotadd }}"
      - "After hot adding, the number of disk: {{ disk_num_guest_after_hotadd }}"

- name: "Verify disk controller and disk number increases 1 in guest OS"
  ansible.builtin.assert:
    that:
      - ctl_num_guest_after_hotadd | int == ctl_num_guest_before_hotadd | int + 1
      - disk_num_guest_after_hotadd | int == disk_num_guest_before_hotadd | int + 1
    fail_msg:
      - "Testing failed at hot adding new {{ test_disk_controller_type }} controller and disk at the same time."
      - "Disk controller number before hot add: {{ ctl_num_guest_before_hotadd }}, after hot add: {{ ctl_num_guest_after_hotadd }}"
      - "Disk number before hot add: {{ disk_num_guest_before_hotadd }}, after hot add: {{ disk_num_guest_after_hotadd }}"

- name: "Initialize new disk and create disk partition in guest OS"
  include_tasks: create_partition_raw_disk.yml
  vars:
    on_new_controller: true
