# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get disk controller number in guest OS before hot adding new disk controller and disk"
  include_tasks: ../utils/win_get_ctl_num.yml
  vars:
    win_ctl_type: "{{ test_disk_controller_type }}"

- name: "Get disk number in guest OS before hot adding new disk controller and disk"
  include_tasks: ../utils/win_get_disk_num.yml

- name: "Set fact of disk controller and disk number before hot adding new disk controller and disk"
  ansible.builtin.set_fact:
    ctl_num_guest_before_add: "{{ ctl_num_guest }}"
    disk_num_guest_before_add: "{{ disk_num_guest }}"

- name: "Set facts of new disk node info"
  ansible.builtin.set_fact:
    new_disk_node_ctl_type: 'non-boot'
    new_disk_node_ctl_bus: "{{ new_vhba_bus_number }}"
    new_disk_node_unit_num: 0

- name: "Print the new disk node info"
  ansible.builtin.debug:
    msg:
      - "New disk will be added to the controller with bus number: {{ new_disk_node_ctl_bus }}"
      - "New disk's unit number will be: {{ new_disk_node_unit_num }}"

- name: "Hot add new disk controller and disk at the same time"
  include_tasks: ../../common/vm_hot_add_ctrl_disk.yml
  vars:
    disk_controller_type: "{{ test_disk_controller_type }}"
    ctrl_number: "{{ new_disk_node_ctl_bus }}"
    unit_number: "{{ new_disk_node_unit_num }}"

- name: "Wait 10 seconds after new disk controller and disk hot add"
  ansible.builtin.pause:
    seconds: 10

- name: "Get disk controller number in guest OS after hot adding new disk controller and disk"
  include_tasks: ../utils/win_get_ctl_num.yml
  vars:
    win_ctl_type: "{{ test_disk_controller_type }}"

- name: "Set fact of disk controller number after hot adding"
  ansible.builtin.set_fact:
    ctl_num_guest_after_add: "{{ ctl_num_guest }}"

- name: "Get disk number in guest OS after hot adding new disk controller and disk"
  include_tasks: ../utils/win_get_disk_num.yml

- name: "Check disk controller and disk in guest OS after hot adding new disk controller and disk"
  include_tasks: check_disk_after_adding.yml
  vars:
    on_new_controller: true
