# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Hot add disk to existing controller
- include_tasks: ../../common/vm_hot_add_remove_disk.yml
  vars:
    disk_operation: 'present'
    disk_controller_type: "{{ test_disk_controller_type }}"
    ctrl_number: "{{ new_vhba_bus_number }}"
    unit_number: 1
- name: "Wait 15 seconds after disk hotadd"
  ansible.builtin.pause:
    seconds: 15

# Get the number of disk in guest OS after hotadd
- include_tasks: ../utils/win_get_disk_num.yml
- name: Set fact of disk number after hotadd
  ansible.builtin.set_fact:
    disk_num_guest_after_hotadd: "{{ disk_num_guest }}"

# When hotadd a NVMe disk to existing controller, disable and re-enable NVMe
# controller in guest OS, then new disk can be recognized
- block:
    - name: "Known issue - workaround of hot adding NVMe disk"
      ansible.builtin.debug:
        msg:
          - "Hot-add NVMe disk is not supported on Windows VM when NVMe Spec v1.0 is emulated. Ignore this known issue."
          - "Disable/re-enable NVMe controller as a workaround for hot adding disk to existing NVMe controller."
      tags:
        - known_issue
    - include_tasks: disable_enable_nvme_device.yml
    # Get the number of disk in guest OS after NVMe controller disable/re-enable
    - include_tasks: ../utils/win_get_disk_num.yml
    - name: "Set fact of disk number after hotadd and NVMe controller disable/re-enable"
      ansible.builtin.set_fact:
        disk_num_guest_after_hotadd: "{{ disk_num_guest }}"
  when:
    - test_disk_controller_type == 'nvme'
    - test_purpose == "hot-add"
    - disk_num_guest_after_hotadd | int != disk_num_guest_before_hotadd | int + 2

- name: "Display the disk number got in guest after hotadd"
  ansible.builtin.debug: var=disk_num_guest_after_hotadd
- name: "Verify disk number increases in guest OS"
  ansible.builtin.assert:
    that:
      - "{{ disk_num_guest_after_hotadd | int == disk_num_guest_before_hotadd | int + 2 }}"
    success_msg: "Disk number increases 2 in guest OS after disk hotadd to new controller and existing controller."
    fail_msg: "Disk number not increase 2, before hotadd: {{ disk_num_guest_before_hotadd }}, after hotadd: {{ disk_num_guest_after_hotadd }}"

# Initialize new disk and create disk partition in guest OS
- include_tasks: create_partition_raw_disk.yml
