# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Parameter 'test_on_boot_ctrl' must be passed when including this tasks file,
# set to 'true' means adding a new disk on the boot disk controller, 'false'
# means adding a new disk to the existing non-boot disk controller.
#
- name: "Get disk number in guest OS before hot adding to existing controller"
  include_tasks: ../utils/win_get_disk_num.yml

- name: "Set fact of disk number before hot adding to existing controller"
  ansible.builtin.set_fact:
    disk_num_guest_before_add: "{{ disk_num_guest }}"

- name: "Set facts of new disk node info"
  ansible.builtin.set_fact:
    new_disk_node_ctl_type: "{{ test_on_boot_ctrl | ternary('boot', 'non-boot') }}"
    new_disk_node_ctl_bus: "{{ test_on_boot_ctrl | ternary(boot_disk_ctl_bus_num, new_vhba_bus_number) }}"
    new_disk_node_unit: "{{ test_on_boot_ctrl | ternary(boot_disk_new_unit_num, 1) }}"

- name: "Print the new disk node info"
  ansible.builtin.debug:
    msg:
      - "New disk will be added to the controller with bus number: {{ new_disk_node_ctl_bus }}"
      - "New disk's unit number will be: {{ new_disk_node_unit }}"

- name: "Hot add a new disk to the existing {{ new_disk_node_ctl_type }} {{ test_disk_controller_type }} controller"
  include_tasks: ../../common/vm_hot_add_remove_disk.yml
  vars:
    disk_operation: 'present'
    disk_controller_type: "{{ test_disk_controller_type }}"
    ctrl_number: "{{ new_disk_node_ctl_bus }}"
    unit_number: "{{ new_disk_node_unit }}"

- name: "Wait 15 seconds after disk hot add"
  ansible.builtin.pause:
    seconds: 15

# This issue may happen when adding new NVMe disk to existing boot or non-boot controller
# while VM boot disk controller must be NVMe
- name: "Handle known issue"
  include_tasks: handle_nvme_boot_known_issue.yml
  when: test_disk_controller_type == 'nvme'

- name: "Get disk number in guest OS after hot adding to existing controller"
  include_tasks: ../utils/win_get_disk_num.yml

- name: "Set fact of disk number after hot adding to existing controller"
  ansible.builtin.set_fact:
    disk_num_guest_after_add: "{{ disk_num_guest }}"

- name: "Print the disk number in guest OS"
  ansible.builtin.debug:
    msg:
      - "Before hot add, the number of disk in guest: {{ disk_num_guest_before_add }}"
      - "After hot add, the number of disk in guest: {{ disk_num_guest_after_add }}"

- name: "Handle known issue"
  when:
    - disk_num_guest_after_add | int != disk_num_guest_before_add | int + 1
    - test_disk_controller_type == 'nvme'
    - test_purpose == "hot-add"
  block:
    - name: "Workaround for the known issue"
      include_tasks: handle_nvme_ops_known_issue.yml

    - name: "Get disk number in guest OS after restart"
      include_tasks: ../utils/win_get_disk_num.yml

    - name: "Reset the fact of disk number after guest OS restart"
      ansible.builtin.set_fact:
        disk_num_guest_after_add: "{{ disk_num_guest }}"

- name: "Verify disk number increases 1 in guest OS"
  ansible.builtin.assert:
    that:
      - disk_num_guest_after_add | int == disk_num_guest_before_add | int + 1
    fail_msg: >-
      After hot adding a new disk to the existing '{{ new_disk_node_ctl_type }}'
      {{ test_disk_controller_type }} controller, disk number in guest OS is:
      {{ disk_num_guest_after_add }}, which is not the same as the expected value
      {{ disk_num_guest_before_add | int + 1 }}.

- name: "Initialize new disk and create disk partition in guest OS"
  include_tasks: create_partition_raw_disk.yml
  vars:
    on_new_controller: false
