# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Hot add a new disk to the existing controller"
  include_tasks: ../../common/vm_hot_add_remove_disk.yml
  vars:
    disk_operation: 'present'
    disk_controller_type: "{{ test_disk_controller_type }}"
    ctrl_number: "{{ new_vhba_bus_number }}"
    unit_number: 1

- name: "Wait 15 seconds after disk hot add"
  ansible.builtin.pause:
    seconds: 15

- name: "Get the number of disk in guest OS after hot add"
  include_tasks: ../utils/win_get_disk_num.yml

- name: "Set fact of disk number after hot add"
  ansible.builtin.set_fact:
    disk_num_guest_after_hotadd2: "{{ disk_num_guest }}"

# Hot add NVMe disk to existing controller, the disk is not recognized
# before guest OS restart or disable/enable NVMe controller.
# Note:
#   Disable/enable operation prompts to request OS restart due to NVMe
# controller disable request is vetoed by storage after OS restart.
# So the workaround here is changed to restart guest OS directly.
# - include_tasks: disable_enable_nvme_device.yml
- name: "Handle known issue"
  when:
    - test_disk_controller_type == 'nvme'
    - test_purpose == "hot-add"
    - disk_num_guest_after_hotadd2 | int != disk_num_guest_before_hotadd1 | int + 1
  block:
    - name: "Known issue - workaround of hot adding NVMe disk to existing controller"
      ansible.builtin.debug:
        msg:
          - "Hot-add NVMe disk is not supported on Windows VM when NVMe Spec v1.0 is emulated. Ignore this known issue."
          - "Restart guest OS as a workaround for hot adding disk to existing NVMe controller."
      tags:
        - known_issue

    - name: "Restart guest OS"
      include_tasks: ../utils/win_shutdown_restart.yml
      vars:
        set_win_power_state: "restart"
    - name: "Get disk number in guest OS after restart"
      include_tasks: ../utils/win_get_disk_num.yml
    - name: "Reset the fact of disk number after guest restart"
      ansible.builtin.set_fact:
        disk_num_guest_after_hotadd2: "{{ disk_num_guest }}"

- name: "Verify disk number increases 1 in guest OS"
  ansible.builtin.assert:
    that:
      - disk_num_guest_after_hotadd2 | int == disk_num_guest_before_hotadd1 | int + 1
    fail_msg:
      - "Testing failed at hot adding new disk to the existing controller." 
      - "Disk number before hot add: {{ disk_num_guest_before_hotadd1 }}, after hot add: {{ disk_num_guest_after_hotadd2 }}"

- name: "Add disk to existing controller"
  ansible.builtin.set_fact:
    add_new_controller: false

- name: "Initialize new disk and create disk partition in guest OS"
  include_tasks: create_partition_raw_disk.yml
