# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Hot remove disks added on the new controller"
  include_tasks: ../../common/vm_hot_add_remove_disk.yml
  vars:
    disk_operation: 'absent'
    ctrl_number: "{{ new_vhba_bus_number }}"
    unit_number: "{{ rm_disk_unit_num }}"
    disk_controller_type: "{{ test_disk_controller_type }}"
  loop: [0, 1]
  loop_control:
    loop_var: rm_disk_unit_num

- name: "Wait 10 seconds after disk hot remove"
  ansible.builtin.pause:
    seconds: 10

- name: "Handle known issue"
  include_tasks: handle_nvme_known_issue.yml
  when:
    - test_disk_controller_type == 'nvme'
    - test_purpose == "hot-add"

- name: "Hot remove new added disk controller"
  include_tasks: ../../common/vm_hot_add_remove_disk_ctrl.yml
  vars:
    disk_controller_ops: "absent"
    disk_controller_type: "{{ test_disk_controller_type }}"
    disk_controller_number: "{{ new_vhba_bus_number }}"

- name: "Wait 10 seconds after disk controller hot remove"
  ansible.builtin.pause:
    seconds: 10

- name: "Get disk controller and disk number in guest OS after hot remove"
  include_tasks: get_guest_disk_ctl_num.yml

- name: "Set fact of the disk controller and disk number after hot remove"
  ansible.builtin.set_fact:
    ctl_num_guest_after_remove: "{{ ctl_num_guest }}"
    disk_num_guest_after_remove: "{{ disk_num_guest }}"

- name: "Check disk controller and disk number after hot remove"
  ansible.builtin.assert:
    that:
      - disk_num_guest_after_remove | int == disk_num_guest_before_hotadd | int
      - ctl_num_guest_after_remove | int == ctl_num_guest_before_hotadd | int
    fail_msg: >-
      After disk controller and disk hot remove,
      disk controller number '{{ ctl_num_guest_after_remove }}', disk number '{{ disk_num_guest_after_remove }}',
      which are not the same as the ones before hot add,
      disk controller number '{{ ctl_num_guest_before_hotadd }}', disk number '{{ disk_num_guest_before_hotadd }}'.
