# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get disk and controller number before hot removing disk from boot disk controller"
  include_tasks: get_guest_disk_ctrl_num.yml
  vars:
    disk_ops_stage: 'before'

- name: "Hot remove disk from boot disk controller"
  include_tasks: ../../common/vm_hot_add_remove_disk.yml
  vars:
    disk_operation: 'absent'
    ctrl_number: "{{ boot_disk_ctrl_bus_num }}"
    unit_number: "{{ boot_ctrl_new_unit_num }}"
    disk_controller_type: "{{ test_disk_ctrl_type }}"

- name: "Wait 10 seconds after hot removing disk"
  ansible.builtin.pause:
    seconds: 10

- name: "Get disk and controller number after hot removing disk from boot disk controller"
  include_tasks: get_guest_disk_ctrl_num.yml
  vars:
    disk_ops_stage: 'after'

- name: "Handle known issue on NVMe disk hot remove"
  include_tasks: handle_nvme_ops_known_issue.yml
  when:
    - disk_num_guest_after | int != disk_num_guest_before | int - 1
    - test_purpose == "hot-add"
    - test_disk_ctrl_type == 'nvme'

- name: "Check disk number after hot removing"
  ansible.builtin.assert:
    that:
      - disk_num_guest_after | int == disk_num_guest_before | int - 1
    fail_msg: >-
      After hot removing the new added disk from boot disk controller, disk number in guest OS is
      '{{ disk_num_guest_after }}', which is not the expected value,
      '{{ disk_num_guest_before | int - 1 }}'.
