# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get disk controller number in guest OS before hot removing disk controller and disk"
  include_tasks: ../utils/win_get_ctl_num.yml
  vars:
    win_ctl_type: "{{ test_disk_controller_type }}"

- name: "Get disk number in guest OS before hot removing disk controller and disk"
  include_tasks: ../utils/win_get_disk_num.yml

- name: "Set fact of disk controller and disk number before hot removing"
  ansible.builtin.set_fact:
    ctl_num_guest_before_remove: "{{ ctl_num_guest }}"
    disk_num_guest_before_remove: "{{ disk_num_guest }}"

- name: "Get VM disk controllers info before hot removing"
  include_tasks: ../../common/vm_get_disk_controller_facts.yml

- name: "Set fact of the number of disks before hot removing"
  ansible.builtin.set_fact:
    disk_num_under_remove: >-
      {{ disk_controller_facts['disk_controller_data'][disk_controller][new_vhba_bus_number | string]['controller_disks_devicekey'] | default([]) }}

- name: "Print the number of the disks under removing"
  ansible.builtin.debug:
    msg: "The number of disks attached to the controller '{{ test_disk_controller_type }}: {{ new_vhba_bus_number }}' is: {{ disk_num_under_remove | length }}"

- name: "Remove the disks attached to the new controller"
  when: disk_num_under_remove | length > 0
  block:
    - name: "Hot remove added disks before"
      include_tasks: ../../common/vm_hot_add_remove_disk.yml
      vars:
        disk_operation: 'absent'
        ctrl_number: "{{ new_vhba_bus_number }}"
        unit_number: "{{ rm_disk_unit_num }}"
        disk_controller_type: "{{ test_disk_controller_type }}"
      loop: "{{ range(0, (disk_num_under_remove | length)) }}"
      loop_control:
        loop_var: rm_disk_unit_num

    - name: "Wait 10 seconds after disk hot remove"
      ansible.builtin.pause:
        seconds: 10

- name: "Get disk number in guest OS after hot removing"
  include_tasks: ../utils/win_get_disk_num.yml

- name: "Set fact of disk number after hot removing"
  ansible.builtin.set_fact:
    disk_num_guest_after_remove: "{{ disk_num_guest }}"

- name: "Print the disk number in guest OS"
  ansible.builtin.debug:
    msg:
      - "Before hot remove, the number of disk in guest: {{ disk_num_guest_before_remove }}"
      - "After hot remove, the number of disk in guest: {{ disk_num_guest_after_remove }}"

- name: "Handle known issue"
  include_tasks: handle_nvme_ops_known_issue.yml
  when:
    - disk_num_guest_after_remove | int != (disk_num_guest_before_remove | int - disk_num_under_remove | length)
    - test_disk_controller_type == 'nvme'
    - test_purpose == "hot-add"

- name: "Hot remove new added disk controller"
  include_tasks: ../../common/vm_hot_add_remove_disk_ctrl.yml
  vars:
    disk_controller_ops: "absent"
    disk_controller_type: "{{ test_disk_controller_type }}"
    disk_controller_number: "{{ new_vhba_bus_number }}"

- name: "Wait 10 seconds after disk controller hot remove"
  ansible.builtin.pause:
    seconds: 10

- name: "Get disk controller number in guest OS after hot removing disk controller and disk"
  include_tasks: ../utils/win_get_ctl_num.yml
  vars:
    win_ctl_type: "{{ test_disk_controller_type }}"

- name: "Get disk number in guest OS after hot removing disk controller and disk"
  include_tasks: ../utils/win_get_disk_num.yml

- name: "Set fact of the disk controller and disk number after hot remove"
  ansible.builtin.set_fact:
    ctl_num_guest_after_remove: "{{ ctl_num_guest }}"
    disk_num_guest_after_remove: "{{ disk_num_guest }}"

- name: "Check disk controller and disk number after hot remove"
  ansible.builtin.assert:
    that:
      - disk_num_guest_after_remove | int == (disk_num_guest_before_remove | int - disk_num_under_remove | length)
      - ctl_num_guest_after_remove | int == ctl_num_guest_before_remove | int - 1
    fail_msg: >-
      After hot removing new added disk controller and disks,
      disk controller number is '{{ ctl_num_guest_after_remove }}', disk number is '{{ disk_num_guest_after_remove }}',
      which are not the expected values,
      disk controller '{{ ctl_num_guest_before_remove | int - 1 }}', disk number
      '{{ disk_num_guest_before_remove | int - disk_num_under_remove | length }}'.
