# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is for disk hot add and hot remove on a new and existing
# LSILogicSAS controller.
#
- name: lsilogicsas_vhba_device_ops
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              Skip test case '{{ ansible_play_name }}' because LSILogicSAS controller type
              is not supported on ARM ESXi host.
            skip_reason: "Not Supported"
          when: esxi_cpu_vendor == 'arm'

        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            create_current_test_folder: true

        - name: "Test run"
          include_tasks: vhba_test.yml
          vars:
            test_disk_ctrl_type: "lsilogicsas"
            test_purpose: "hot-add"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
