# Copyright 2022-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for check hotadd, hot remove disk
# on a new and existing NVMe controller with NVMe Spec 1.3 enabled
# manually.
# Notes:
#   Please refer to the release notes of ESXi 8.0.2:
# https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/
# release-notes/esxi-update-and-patch-release-notes/vsphere-esxi-802-release-notes.html
# Default NVMe version 1.3 for Windows virtual machines:
# Starting with vSphere 8.0 Update 2, the NVMe version of Windows Server 2022
# or Windows 11 and later virtual machines with hardware version 21 and later,
# and a virtual NVMe controller, is set to 1.3 by default.
# Set this test case result to "Not Applicable" in above situation.
#
- name: nvme_vhba_device_ops_spec13
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            create_current_test_folder: true

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              The NVMe 1.3 Spec is supported from ESXi 7.0.2 hardware version 19.
              Skip this test case due to VM's hardware version is '{{ vm_hardware_version_num }}'.
            skip_reason: "Not Supported"
          when: vm_hardware_version_num and vm_hardware_version_num | int < 19

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              Skip testing on this guest OS '{{ guest_os_ansible_distribution }}', since
              Windows Server 2019 and earlier server releases do not contain the fix of hot adding/removing NVMe disk issue,
              so skip this test case and only run test case 'nvme_vhba_device_ops' with workaround.
            skip_reason: "Not Applicable"
          when:
            - guest_os_product_type == 'server'
            - guest_os_ansible_kernel is version('10.0.20348.0', '<')

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              Skip testing on this guest OS '{{ guest_os_ansible_distribution }}' with VM hardware version
              '{{ vm_hardware_version_num }}', since NVMe version is 1.3 by default for Windows Server 2022,
              Windows 11 and later VMs with hardware version 21 on ESXi 8.0.2 and later.
              So skip this test case and only run test case 'nvme_vhba_device_ops' with default NVMe v1.3.
            skip_reason: "Not Applicable"
          when:
            - vm_hardware_version_num | int >= 21
            - (guest_os_product_type == 'server' and guest_os_build_num | int >= 20348) or 
              (guest_os_product_type == 'client' and guest_os_build_num | int >= 22000)

        - name: "Test run"
          include_tasks: vhba_test.yml
          vars:
            test_disk_ctrl_type: "nvme"
            test_purpose: "hot-add-spec13"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
