# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for test on hot extend NVMe disk size
# with NVMe Spec 1.3 enabled on VM.
#
- name: nvme_disk_hot_extend_spec13
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml

        - name: "Test run"
          include_tasks: vhba_test.yml
          vars:
            test_disk_controller_type: "nvme"
            test_purpose: "hot-extend"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
