# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for test on hot extend NVMe disk size
# with NVMe Spec 1.3 enabled on VM.
#
- name: nvme_disk_hot_extend_spec13
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            create_current_test_folder: true

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              Skip testing on this guest OS '{{ guest_os_ansible_distribution }}', since
              Windows Server 2019 and earlier releases do not contain the fix of hot adding/removing NVMe disk issue,
              so skip this test case and only run test case 'nvme_vhba_device_ops' with workaround.
            skip_reason: "Not Applicable"
          when:
            - guest_os_product_type == 'server'
            - guest_os_ansible_kernel is version('10.0.20348.0', '<')

        - name: "Test run"
          include_tasks: vhba_test.yml
          vars:
            test_disk_ctrl_type: "nvme"
            test_purpose: "hot-extend"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
