# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for test on hot extend NVMe disk size
# with NVMe Spec 1.3 enabled on VM.
#
- name: nvme_disk_hot_extend_spec13
  hosts: localhost
  gather_facts: no
  vars_files:
    - "{{ testing_vars_file | default('../../vars/test.yml') }}"
  tasks:
    - block:
        - include_tasks: ../setup/test_setup.yml
        - include_tasks: vhba_test.yml
          vars:
            test_disk_controller_type: "paravirtual"
            test_purpose: "hot-extend"
      rescue:
        - include_tasks: ../../common/test_rescue.yml
