# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for check hot add, hot remove disk
# on a new and existing NVMe controller.
# Note: after disk hot add, need to disable and re-enable NVMe
# device in guest OS to recognize the new disk, after disk hot
# remove, need to restart guest OS to take effort.
#
- name: nvme_vhba_device_ops
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            create_current_test_folder: true

        - name: "Test run"
          include_tasks: vhba_test.yml
          vars:
            test_disk_controller_type: "nvme"
            test_purpose: "hot-add"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
