# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for check hotadd, hot remove disk
# on NVMe controller with NVMe Spec 1.3 enabled.
#
- name: nvme_vhba_device_ops_spec13
  hosts: localhost
  gather_facts: no
  vars_files:
    - "{{ testing_vars_file | default('../../vars/test.yml') }}"
  tasks:
    - block:
        - include_tasks: ../setup/test_setup.yml
        - include_tasks: vhba_test.yml
          vars:
            test_disk_controller_type: "nvme"
            test_purpose: "hot-add-spec13"
      rescue:
        - include_tasks: ../../common/test_rescue.yml
