# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is for disk hot add and hot remove on a new and existing PVSCSI
# controller. Test case result is 'Blocked' when there is no PVSCSI driver in guest OS,
# which means either VMware Tools is not running, or guest OS does not have inbox PVSCSI driver.
#
- name: paravirtual_vhba_device_ops
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            create_current_test_folder: true

        # Skip test case if no pvscsi driver in guest OS, no matter it's from inbox or VMware Tools
        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Test case '{{ current_testcase_name }}' is blocked because guest OS has no inbox PVSCSI driver or VMware Tools is not installed"
            skip_reason: "Blocked"
          when:
            - not vmtools_is_running
            - not guest_os_with_inbox_drivers

        - name: "Test run"
          include_tasks: vhba_test.yml
          vars:
            test_disk_ctrl_type: "paravirtual"
            test_purpose: "hot-add"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
