# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# For hot add sata disk test, set the boot disk label first since
# boot order may be changed after disk hot add when VM with BIOS firmware.
# For hot add disk test, get VM boot disk controller info first
# since there is test step of hot adding disk to boot disk controller.
#
- name: "Get VM boot disk and controller info"
  include_tasks: get_vm_boot_disk_info.yml
  when: boot_disk_info_retrieved is undefined

- name: "Get new disk controller bus number"
  include_tasks: ../../common/vm_get_new_vhba_bus_number.yml
  vars:
    disk_controller_facts_data: "{{ disk_ctls_before_hotadd }}"
    new_vhba_type: "{{ disk_controller }}"

- name: "Enable NVMe spec 1.3"
  include_tasks: enable_vm_nvme_spec13.yml
  when:
    - test_disk_controller_type == 'nvme'
    - test_purpose in ["hot-add-spec13", "hot-extend"]

- name: "Set fact of the conditions of NVMe known issue on Windows Server 2025"
  ansible.builtin.set_fact:
    nvme_boot_known_issue: |-
      {%- if (test_disk_controller_type == 'nvme' and win_boot_disk_ctl_type == 'nvme' and guest_os_ansible_distribution is search('2025')) -%}true
      {%- else -%}false
      {%- endif -%}
