# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Notes on Windows VM disk controller types:
# - paravirtual: inbox pvscsi driver or VMware Tools installed in guest OS.
# - lsilogic: no inbox driver in Windows guest OS now, so no testing.
# - buslogic: not supported in 64bit Windows guest OS, so no testing.
#
- name: "Get VM current disk controller info"
  include_tasks: get_vm_disk_ctl_info.yml

- name: "Print whether can add new disk controller"
  ansible.builtin.debug:
    msg: "Can add a new '{{ disk_controller }}' controller since existing controller number {{ disk_controller_count }} < 4."
  when: disk_controller_count | int < 4

- name: "Skip test case"
  include_tasks: ../../common/skip_test_case.yml
  vars:
    skip_msg: "Test case is blocked due to controller '{{ disk_controller }}' number is already 4: {{ disk_controller_count }}."
    skip_reason: "Blocked"
  when: disk_controller_count | int == 4

- name: "Preparation for the testing"
  include_tasks: vhba_test_prepare.yml

- name: "Execute disk hot add test"
  when: >
    (test_purpose == "hot-add") or
    (test_purpose == "hot-add-spec13")
  block:
    - name: "Test on adding a new disk on NVMe boot disk controller"
      when:
        - test_disk_controller_type == 'nvme'
        - win_boot_disk_ctl_type == 'nvme'
      block:
        - name: "Add a new NVMe disk to boot disk controller"
          include_tasks: hotadd_disk_existing_ctrl.yml
          vars:
            test_on_boot_ctrl: true
        - name: "Remove the new added disk to boot disk controller"
          include_tasks: hotremove_disk_boot_ctrl.yml

    - name: "Test on adding a new disk on the new disk controller at the same time"
      include_tasks: hotadd_disk_new_ctrl.yml

    - name: "Test on adding a new disk on the existing controller added above"
      include_tasks: hotadd_disk_existing_ctrl.yml
      vars:
        test_on_boot_ctrl: false

    - name: "Test on removing the new added disks and disk controller"
      include_tasks: hotremove_disk_and_ctrl.yml

- name: "Execute disk hot extend test"
  include_tasks: hot_extend_disk_test.yml
  when: test_purpose == "hot-extend"
