# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get the number of controllers and disks in guest OS before hotadd
- include_tasks: get_guest_disk_ctl_num.yml
- name: Set fact of the controller number and disk number before hotadd
  ansible.builtin.set_fact:
    ctl_num_guest_before_hotadd: "{{ ctl_num_guest }}"
    disk_num_guest_before_hotadd: "{{ disk_num_guest }}"

# Enable NVMe spec 1.3
- include_tasks: enable_vm_nvme_spec13.yml
  when:
    - test_purpose == "hot-add-spec13" or test_purpose == "hot-extend"

# Get the NVMe controller device instance id list before hotadd
- block:
    - include_tasks: ../utils/win_get_nvme_ctl_inst_id_list.yml
    - name: Set fact of the NVMe controller instance id list before hotadd
      ansible.builtin.set_fact:
        nvme_ctl_inst_id_list_before: "{{ nvme_ctl_instance_id_list }}"
  when:
    - test_disk_controller_type == "nvme"
    - test_purpose == "hot-add"
