# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Notes on Windows VM disk controller types:
# - paravirtual: inbox pvscsi driver or VMware Tools installed in guest OS.
# - lsilogic: no inbox driver in Windows guest OS now, so no testing.
# - buslogic: not supported in 64bit Windows guest OS, so no testing.
#
- name: "Initialize the fact of whether can add new disk controller"
  ansible.builtin.set_fact:
    add_new_controller: false

- name: "Get VM current disk controller info"
  include_tasks: get_vm_disk_ctl_info.yml

- name: "Set fact of whether can add new disk controller"
  ansible.builtin.set_fact:
    add_new_controller: "{{ disk_controller_count | int < 4 }}"

- name: "Skip test case"
  include_tasks: ../../common/skip_test_case.yml
  vars:
    skip_msg: "Test case is blocked due to controller '{{ disk_controller }}' number is already 4: {{ disk_controller_count }}."
    skip_reason: "Blocked"
  when: not add_new_controller

- name: "Preparation for the testing"
  include_tasks: vhba_test_prepare.yml

- name: "Execute disk hot add test"
  when: >
    (test_purpose == "hot-add") or
    (test_purpose == "hot-add-spec13")
  block:
    - name: "Test on adding new disk on NVMe boot disk controller"
      include_tasks: hotadd_vm_disk_existing_ctrl.yml
      when: test_disk_controller_type == 'nvme'

    - name: "Test on adding new disk on new disk controller at the same time"
      include_tasks: hotadd_vm_disk_new_ctrl.yml

    - name: "Test on adding new disk on the existing controller"
      include_tasks: hotadd_vm_disk_existing_ctrl.yml

    - name: "Test on remove new added disks and disk controller"
      include_tasks: hotremove_vm_disk_ctrl.yml

- name: "Execute disk hot extend test"
  include_tasks: hot_extend_disk_test.yml
  when: test_purpose == "hot-extend"
