# Copyright 2023-2026 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Initialize variables"
  ansible.builtin.set_fact:
    vm_nested_virt_status: false
    wsl_distribution_name: "Ubuntu-24.04"

# Get CPU Hardware virtualization status
- name: "Get VM Hardware virtualization status"
  include_tasks: ../../common/vm_get_config.yml
  vars:
    property_list: ['config.nestedHVEnabled']

- name: "Set fact of VM CPU Hardware virtualization status"
  ansible.builtin.set_fact:
    vm_nested_virt_status: "{{ vm_config.config.nestedHVEnabled }}"
  when:
    - vm_config.config is defined
    - vm_config.config.nestedHVEnabled is defined

- name: "Display VM CPU Hardware virtualization status"
  ansible.builtin.debug:
    msg: "VM CPU Hardware virtualization is enabled: {{ vm_nested_virt_status }}"

- name: "Enable CPU Hardware virtualization"
  when: not vm_nested_virt_status | bool
  block:
    - name: "Shutdown VM"
      include_tasks: ../utils/win_shutdown_restart.yml
      vars:
        set_win_power_state: "shutdown"

    - name: "Eanble CPU Hardware virtualization for the VM"
      include_tasks: ../../common/vm_set_nested_virtual.yml
      vars:
        vm_nested_virt: true

    - name: "Poweron the VM"
      include_tasks: ../../common/vm_set_power_state.yml
      vars:
        vm_power_state_set: 'powered-on'
