# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Test case block"
  block:
    - name: "Test setup"
      include_tasks: ../setup/test_setup.yml
      vars:
        create_test_log_folder: true

    - name: "Prepare for {{ adapter_type }} network adapter testing"
      include_tasks: prepare_network_device_test.yml

    - name: "Prepare network environment for new network adapter"
      include_tasks: ../../common/network_testbed_setup.yml

    - name: "Set fact of the static IP address info for new network adapter"
      ansible.builtin.set_fact:
        new_nic_ipv4: "{{ network_env_nic_ip }}"
        new_nic_net_prefix: "{{ network_env_net_prefix }}"
        new_nic_gateway: "{{ network_env_gateway }}"
      when: vds_network_is_setup is defined and vds_network_is_setup

    - name: "Hot add a new {{ adapter_type }} network adapter on VM and apply network config"
      include_tasks: hot_add_network_adapter.yml
      vars:
        new_nic_ipv4_method: "{{ (vds_network_is_setup is defined and vds_network_is_setup) | ternary('static', 'dhcp') }}"

    - name: "Validate network adapter status changes"
      include_tasks: network_status_validate.yml

    - name: "Hot remove the new {{ adapter_type }} network adapter"
      include_tasks: hot_remove_network_adapter.yml
  rescue:
    - name: "Collect Linux guest OS information for triage"
      include_tasks: ../setup/linux_test_rescue.yml

    - name: "Test case failure"
      include_tasks: ../../common/test_rescue.yml
