# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Disable power save in Windows guest OS"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: "powercfg /change monitor-timeout-ac 0; powercfg /change disk-timeout-ac 0; powercfg /change standby-timeout-ac 0; powercfg /change hibernate-timeout-ac 0;"

- name: "Disable firewall in Windows guest OS"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: "netsh advfirewall set allprofiles state off"

# By default, Windows will restart automatically when BSOD,
# disable this automatic reboot when failure
- name: "Disable auto reboot in Windows guest OS"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: "Get-CimInstance Win32_OSRecoveryConfiguration | Set-CimInstance -Property @{AutoReboot=$False}"

- name: "Disable Microsoft Store service in Windows Client"
  include_tasks: ../utils/win_disable_store_auto_update.yml
  when: guest_os_product_type == "client"

- name: "Disable Shutdown event tracker in Windows Server"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: >-
      REG ADD "HKLM\Software\Policies\Microsoft\Windows NT\Reliability" /v "ShutdownReasonUI" /t REG_DWORD /d 0 /f;
      REG ADD "HKLM\SOFTWARE\Policies\Microsoft\Windows NT\Reliability" /v "ShutdownReasonOn" /t REG_DWORD /d 0 /f
  when: guest_os_product_type == "server"

- name: "Disable UAC"
  include_tasks: ../utils/win_disable_uac.yml

- name: "Restart guest OS"
  include_tasks: ../utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "restart"
