# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for check guest OS customization (GOSC)
# with DHCP network configuration. If VMware Tools is not installed,
# the test result is 'Blocked'.
# Note: VM guest OS customization requires vCenter server.
#
- name: gosc_sanity_dhcp
  hosts: localhost
  gather_facts: false
  vars:
    gosc_network_type: "dhcp"
  tasks:
    - name: "GOSC test with DHCP network configure"
      include_tasks: win_gosc_workflow.yml
