# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Set the parameters in static and DHCP GOSC specifications
# Note: refer to this page to set time zone id and name:
# https://msdn.microsoft.com/en-us/library/ms912391.aspx
#
- name: "Prepare router VM, vSwitch and portgroup"
  include_tasks: ../../common/network_testbed_setup.yml
  when:
    - (router_vm_deployed is undefined) or (not router_vm_deployed | bool)
    - customize_network_type == "static"

- name: "Set fact of the common parameters in static and DHCP GOSC spec"
  ansible.builtin.set_fact:
    customize_gos_hostname: 'gosc-test-win'
    customize_domain: "autotest.com"
    customize_autologon: true
    customize_autologon_count: 10
    customize_logon_password: 'B1gd3m0z!'
    customize_timezone_id: '2'
    customize_timezone_name: "Hawaiian Standard Time"
    gosc_dns_servers: ['192.168.0.1', '192.168.0.2']
    customize_runonce_echo_string: 'Windows gosc automation test'

- name: "Set fact of the run once command"
  ansible.builtin.set_fact:
    customize_runonce: "cmd.exe /c echo {{ customize_runonce_echo_string }} > C:\\gosc_runonce.txt"

- name: "Set fact of the static network config parameters"
  ansible.builtin.set_fact:
    customize_ip: '192.168.192.10'
    customize_gateway: "{{ vlan_gateway }}"
    customize_netmask: '255.255.255.0'
    customize_network: "{{ portgroup_name }}"
  when: customize_network_type == "static"

- name: "Set fact of the DHCP network config parameter"
  ansible.builtin.set_fact:
    customize_network: "{{ gosc_dhcp_network | default('VM Network') }}"
  when: customize_network_type == "dhcp"

- name: "Set fact of default Windows dir"
  ansible.builtin.set_fact:
    win_dir: '$env:windir'
- name: "Get directory path in Windows guest OS"
  include_tasks: ../utils/win_get_path.yml
  vars:
    win_get_path_specified: "{{ win_dir }}"
- name: "Set fact of the absolute path of Windows dir"
  ansible.builtin.set_fact:
    win_dir: "{{ win_get_path_absolute }}"
- name: "Print Windows dir"
  ansible.builtin.debug:
    msg: "Windows GOSC log files in Windows dir: {{ win_dir }}"

# Uninstall OneDrive in Windows 11 for the known 3rd-party issue
# Parameter 'uninstall_onedrive' is used for internal testing only
- name: "Uninstall OneDrive"
  include_tasks: uninstall_onedrive.yml
  when:
    - uninstall_onedrive is defined
    - uninstall_onedrive | bool
    - guest_os_ansible_distribution_ver is version('10.0.22000.0', '>=')
    - guest_os_product_type | lower == 'client'

# Disable BitLocker which will cause sysprep failure
# BitLocker is not installed by default on Windows Server
- name: "Disable BitLocker"
  when: guest_os_product_type | lower == 'client'
  block:
    - name: "Get BitLocker service status"
      include_tasks: ../utils/win_get_service_status.yml
      vars:
        win_service_name: "BDESVC"

    - name: "Stop and disable BitLocker service in guest OS"
      include_tasks: ../utils/win_execute_cmd.yml
      vars:
        win_powershell_cmd: "Set-Service -Name BDESVC -Status stopped -StartupType disabled"
      when: service_status == "Running"

    - name: "Decrypt Bitlocker volumes"
      include_tasks: ../utils/win_decrypt_bitlocker_volume.yml

- name: "Shutdown guest OS before execute GOSC"
  include_tasks: ../utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "shutdown"
