# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get new block device"
  ansible.builtin.set_fact:
    device: "{{ new_device_list | difference(old_device_list) }}"
- name: "Print new device block name"
  ansible.builtin.debug: var=device
- name: "Check new device file is created"
  ansible.builtin.assert:
    that:
      - device | length == 1
    fail_msg: "Hotadd disk failed due to no new disk device on VM."
    success_msg: "Hotadd disk succeed, new disk device on VM."

- name: "Set new device block filename"
  ansible.builtin.set_fact:
    device_name: "{{ device[0] }}"
- name: "Print new device block filename"
  ansible.builtin.debug: var=device_name

- name: "Format partition on new disk"
  ansible.builtin.shell: |
    set -o pipefail
    (echo n; echo p; echo; echo; echo; echo w) | fdisk "/dev/{{ device_name }}"
  args:
    executable: /bin/bash
  become: yes
  delegate_to: "{{ vm_guest_ip }}"

- name: "Set fact of partition name"
  ansible.builtin.set_fact:
    partition_name: "{{ device_name }}1"
  when: new_disk_ctrl_type != "nvme"

- name: "Set fact of partition name"
  ansible.builtin.set_fact:
    partition_name: "{{ device_name }}p1"
  when: new_disk_ctrl_type == "nvme"

- name: "Print partition name"
  ansible.builtin.debug: var=partition_name

- name: "Set fact of device path"
  ansible.builtin.set_fact:
    device_path: "/dev/{{ partition_name }}"
- name: "Print device path"
  ansible.builtin.debug: var=device_path

- name: "Create ext4 file system"
  ansible.builtin.command: "mkfs.ext4 {{ device_path }}"
  become: yes
  delegate_to: "{{ vm_guest_ip }}"
