# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for deploying new Windows VM and installing
# guest OS in VM automatically on VMware Workstation using 
# Autounattend.xml file when 'dh_vm_deploy_method' is set to 'iso'.
#
- name: dh_deploy_vm
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../../common/dh_test_setup.yml
          vars:
            create_dh_test_folder: true
            require_dh_vm_exists: "{{ true if (dh_new_vm is undefined or not dh_new_vm | bool) else false }}"

        - name: "Skip test case"
          include_tasks: ../../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to 'dh_new_vm' is set to '{{ dh_new_vm | default(false) }}' and got VM exists: '{{ dh_vm_exists }}'"
            skip_reason: "Skipped"
          when:
            - dh_new_vm is undefined or not dh_new_vm | bool
            - dh_vm_exists or dh_vm_vmx_exists

        - name: "Make sure no VM with same name exists"
          ansible.builtin.assert:
            that:
              - not dh_vm_exists
              - not dh_vm_vmx_exists
            fail_msg: "VM with path '{{ dh_vm_vmx_path }}' exists, please set parameter 'dh_vm_name' or 'dh_vm_path' to other values."
          when: dh_new_vm is defined and dh_new_vm | bool

        - name: "Deploy VM on Windows host"
          include_tasks: deploy_vm_windows_host.yml 
          when: host_machine_type == "windows"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/dh_test_rescue.yml
          vars:
            exit_testing_when_fail: true
