# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Set VM default or preferred configurations if corresponding parameters
# are not set in vars file.
- name: "Set VM firmware to EFI"
  ansible.builtin.set_fact:
    dh_vm_firmware: 'efi'
  when: dh_vm_firmware is undefined or not dh_vm_firmware

- name: "Set VM secure boot status"
  ansible.builtin.set_fact:
    dh_vm_secureboot_enabled: "False"
  when:
    - dh_vm_secureboot_enabled is undefined
    - dh_vm_firmware | lower == 'efi'

- name: "Set VM CPU number"
  ansible.builtin.set_fact:
    dh_vm_cpu_number: 2
  when: dh_vm_cpu_number is undefined or not dh_vm_cpu_number

- name: "Set VM CPU cores per socket number"
  ansible.builtin.set_fact:
    dh_vm_cpu_cores_per_socket: 1 
  when: dh_vm_cpu_cores_per_socket is undefined or not dh_vm_cpu_cores_per_socket

- name: "Set VM memory size in MB"
  ansible.builtin.set_fact:
    dh_vm_memory_mb: 2048
  when: dh_vm_memory_mb is undefined or not dh_vm_memory_mb

- name: "Set VM disk size in GB"
  ansible.builtin.set_fact:
    dh_vm_boot_disk_size_gb: 60
  when: dh_vm_boot_disk_size_gb is undefined or not dh_vm_boot_disk_size_gb
- name: "Set VM disk size to 64GB for Windows 11"
  ansible.builtin.set_fact:
    dh_vm_boot_disk_size_gb: 64
  when:
    - dh_vm_boot_disk_size_gb | int < 64
    - dh_vm_guest_id == "windows11-64"

- name: "Set fact of VM boot disk controller type"
  ansible.builtin.set_fact:
    dh_vm_network_adapter: "nvme"
  when: dh_vm_boot_disk_controller is undefined or not dh_vm_boot_disk_controller

- name: "Set fact of VM network adapter type"
  ansible.builtin.set_fact:
    dh_vm_network_adapter: "e1000e"
  when: dh_vm_network_adapter is undefined or not dh_vm_network_adapter
