# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is ued for check VGAuth service status in guest OS when
# VMware Tools is installed and running. Test case result will be 'No Run'
# if VMware Tools is not installed or not running.
#
- name: vgauth_check_service
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            skip_test_no_vmtools: true

        - name: "Get VMware Tools services list"
          include_tasks: ../utils/win_get_vmtools_service_list.yml

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              Skip test case '{{ ansible_play_name }}' because 'VGAuthService' is not available in the guest OS,
              the installed services and their status are '{{ vmtools_service_dict }}'.
            skip_reason: "Not Supported"
          when: >
            (vmtools_service_dict.keys() | length == 0) or
            ("'VGAuthService' not in vmtools_service_dict.keys()")

        - name: "Verify 'VGAuthService' is running"
          ansible.builtin.assert:
            that:
              - vmtools_service_dict['VGAuthService'] == "Running"
            fail_msg: "Service 'VGAuthService' is not running in guest OS, VMware Tools services status '{{ vmtools_service_dict }}'."
            success_msg: "Service 'VGAuthService' is running in guest OS."
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
