# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# If boot disk controller is pvscsi or pvscsi first installer is "Windows",
# then pvscsi driver is not uninstalled
- name: "Check pvscsi driver"
  block:
    - include_tasks: ../utils/win_get_device_driver.yml
      vars:
        device_desc_keyword: 'pvscsi'
    - name: "Set fact of the loaded pvscsi driver info after VMware Tools uninstall"
      ansible.builtin.set_fact:
        win_pvscsi_after_uninstall: "{{ win_guest_device_driver }}"
    - name: "Check pvscsi driver version before and after VMware Tools uninstall"
      ansible.builtin.assert:
        that:
          - win_pvscsi_after_uninstall.DriverVersion is defined
          - win_pvscsi_before_uninstall.DriverVersion is defined
          - win_pvscsi_after_uninstall.DriverVersion == win_pvscsi_before_uninstall.DriverVersion
        fail_msg: "After VMware Tools uninstall, the kept pvscsi version '{{ win_pvscsi_after_uninstall.DriverVersion }}' is not the same as the one before '{{ win_pvscsi_before_uninstall.DriverVersion }}'."
  when: >
    (win_boot_disk_ctl_type == 'paravirtual') or
    (win_pvscsi_vmxnet3_installers.pvscsi[0] == 'Windows')

# If vmxnet3 first installer is "Windows", then vmxnet3 driver is not uninstalled
- name: "Check vmxnet3 driver"
  block:
    - include_tasks: ../utils/win_get_device_driver.yml
      vars:
        device_desc_keyword: 'vmxnet3'
    - name: "Set fact of the loaded vmxnet3 driver info after VMware Tools uninstall"
      ansible.builtin.set_fact:
        win_vmxnet3_after_uninstall: "{{ win_guest_device_driver }}"
    - name: "Check vmxnet3 driver version before and after VMware Tools uninstall"
      ansible.builtin.assert:
        that:
          - win_vmxnet3_after_uninstall.DriverVersion is defined
          - win_vmxnet3_before_uninstall.DriverVersion is defined
          - win_vmxnet3_after_uninstall.DriverVersion == win_vmxnet3_before_uninstall.DriverVersion
        fail_msg: "After VMware Tools uninstall, the kept vmxnet3 version '{{ win_vmxnet3_after_uninstall.DriverVersion }}' is not the same as before '{{ win_vmxnet3_before_uninstall.DriverVersion }}'."
  when:
    - win_pvscsi_vmxnet3_installers.vmxnet3[0] == 'Windows'
