# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# If there is inbox pvscsi driver, pvscsi service is started
# and it's installer value is "Windows", so VMware Tools uninstall
# will not uninstall pvscsi driver
#
- include_tasks: ../utils/win_get_device_driver.yml
  vars:
    device_desc_keyword: 'pvscsi'
- name: "Set fact of the loaded pvscsi driver info after VMware Tools uninstall"
  ansible.builtin.set_fact:
    win_pvscsi_after_uninstall: "{{ win_guest_device_driver }}"
- name: "Check pvscsi driver version after VMware Tools uninstall"
  ansible.builtin.assert:
    that:
      - win_pvscsi_after_uninstall.DriverVersion is defined
      - win_pvscsi_before_uninstall.DriverVersion is defined
      - win_pvscsi_after_uninstall.DriverVersion == win_pvscsi_before_uninstall.DriverVersion
    fail_msg: "After VMware Tools uninstall, the kept pvscsi version '{{ win_pvscsi_after_uninstall.DriverVersion }}' is not the same as the one before '{{ win_pvscsi_before_uninstall.DriverVersion }}'."
