# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get VMware Tools status after uninstall
- include_tasks: ../../common/vm_get_vmtools_status.yml
- name: "Verify VMware Tools is not running and not installed after uninstall"
  ansible.builtin.assert:
    that:
      - vmtools_is_installed is defined
      - not vmtools_is_installed | bool
      - vmtools_is_running is defined
      - not vmtools_is_running | bool
    fail_msg: "Either VMware Tools status: '{{ vmtools_is_installed }}' is still installed or running: '{{ vmtools_is_running }}' after uninstall."

- name: "Check inbox drivers are loaded after VMware Tools uninstall"
  block:
    - include_tasks: ../utils/win_get_problem_device.yml
    
    # Known issue on VMware Tools 12.1.0 and earlier versions
    - name: "Known issue - ignore inbox drivers not loaded after VMware Tools uninstall"
      ansible.builtin.debug:
        msg:
          - "Get problem device in guest OS: {{ gos_problem_device_list }}"
          - "Inbox pvscsi or vmxnet3 drivers are not loaded successfully after VMware Tools uninstall, ignore this known issue on VMware Tools 12.1.0 and earlier versions."
      tags:
        - known_issue
      when:
        - vmtools_version is defined
        - vmtools_version is version('12.1.0', '<=')
        - gos_has_problem_device is defined and gos_has_problem_device

    - name: "Check no problem device listed"
      ansible.builtin.assert:
        that:
          - gos_has_problem_device is defined
          - not gos_has_problem_device
        fail_msg: "Problem devices found in guest OS, please check listed problem devices: {{ gos_problem_device_list }}"
      when: vmtools_version is undefined or vmtools_version is version('12.1.0', '>')

    # Get loaded pvscsi and vmxnet3 driver version
    - include_tasks: ../utils/win_get_device_driver.yml
      vars:
        device_desc_keyword: 'pvscsi'
    - name: "Set fact of the loaded pvscsi driver info"
      ansible.builtin.set_fact:
        win_pvscsi_after_uninstall: "{{ win_guest_device_driver }}"
    - include_tasks: ../utils/win_get_device_driver.yml
      vars:
        device_desc_keyword: 'vmxnet3'
    - name: "Set fact of the loaded vmxnet3 driver info"
      ansible.builtin.set_fact:
        win_vmxnet3_after_uninstall: "{{ win_guest_device_driver }}"
    - name: "Check pvscsi and vmxnet3 drivers are the inbox ones"
      ansible.builtin.assert:
        that:
          - win_pvscsi_after_uninstall.Signer is defined
          - win_pvscsi_after_uninstall.Signer == "Microsoft Windows"
          - win_vmxnet3_after_uninstall.Signer is defined
          - win_vmxnet3_after_uninstall.Signer == "Microsoft Windows"
          - win_pvscsi_after_uninstall.DriverVersion is defined
          - win_pvscsi_after_uninstall.DriverVersion == '1.3.15.0'
          - win_vmxnet3_after_uninstall.DriverVersion is defined
          - win_vmxnet3_after_uninstall.DriverVersion == '1.8.17.0' 
        fail_msg: "Loaded pvscsi driver '{{ win_pvscsi_before_uninstall }}', or vmxnet3 driver '{{ win_vmxnet3_before_uninstall }}' is not inbox driver after uninstalling VMware Tools."
  when:
    - guest_os_with_inbox_drivers is defined
    - guest_os_with_inbox_drivers
