# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get VMware Tools status after uninstall
- include_tasks: ../../common/vm_get_vmtools_status.yml
- name: "Verify VMware Tools is not running and not installed after uninstall"
  ansible.builtin.assert:
    that:
      - vmtools_is_installed is defined
      - not vmtools_is_installed | bool
      - vmtools_is_running is defined
      - not vmtools_is_running | bool
    fail_msg: "Either VMware Tools status: '{{ vmtools_is_installed }}' is still installed or running: '{{ vmtools_is_running }}' after uninstall."

# Only execute following check when there are inbox drivers in guest OS
- name: "Handle there are inbox drivers in guest OS situation"
  block:
    - include_tasks: check_driver_not_uninstalled.yml
    - include_tasks: check_driver_inbox_loaded.yml
  when:
    - guest_os_with_inbox_drivers is defined
    - guest_os_with_inbox_drivers
