# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for test VMware Tools uninstall in
# Windows guest OS.
#
- name: wintools_uninstall_verify
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml

        # VMware Tools status got in test_setup before this test
        - name: "Set fact of the VMware Tools status before uninstall"
          ansible.builtin.set_fact:
            vmtools_is_installed_before: "{{ vmtools_is_installed }}"
            vmtools_is_running_before: "{{ vmtools_is_running }}"
        - name: "Display the VMware Tools status before uninstall"
          ansible.builtin.debug:
            msg: "VMware Tools installed: {{ vmtools_is_installed_before }}, running: {{ vmtools_is_running_before }}"

        - name: "Skip test case when VMware Tools is not installed"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Test case '{{ ansible_play_name }}' is blocked because VMware Tools installed: {{ vmtools_is_installed_before }}, running: {{ vmtools_is_running_before }}"
            skip_reason: "Blocked"
          when: not vmtools_is_installed_before

        - name: "Check VMware Tools is running before uninstall"
          ansible.builtin.fail:
            msg: "VMware Tools installed: {{ vmtools_is_installed_before }}, running: {{ vmtools_is_running_before }}"
          when: not vmtools_is_running_before

        - name: "Make sure PVSCSI controller and VMXNET3 network adatper exist"
          include_tasks: prepare_pvscsi_vmxnet3_device.yml
          when:
            - esxi_cpu_vendor != 'arm'
            - guest_os_with_inbox_drivers

        # In Windows Server 2012 R2 or older OS there is no cmdlet 'Get-PnpDevice',
        # so here only check in newer OS
        - name: "Check if there is problem device in Device Manager"
          include_tasks: ../wintools_complete_install_verify/check_problem_device.yml
          when: guest_os_ansible_distribution_ver is version('6.3.9600.0', '>')

        - name: "Uninstall VMware Tools"
          include_tasks: uninstall_vmtools.yml

        - name: "Verify PVSCSI and VMXNET3 drivers"
          include_tasks: verify_drivers_status.yml
          when:
            - esxi_cpu_vendor != 'arm'
            - guest_os_with_inbox_drivers

        - name: "Cleanup network configurations for added network adapter"
          when:
            - esxi_cpu_vendor != 'arm'
            - guest_os_with_inbox_drivers
            - new_network_adapter_mac is defined
            - new_network_adapter_mac
          block:
            - name: "Remove added network adapter"
              include_tasks: ../../common/vm_remove_network_adapter.yml
              vars:
                netadapter_mac_addr: "{{ new_network_adapter_mac }}"
            - name: "Remove added portgroup"
              include_tasks: ../../common/esxi_remove_portgroup.yml
              vars:
                vswitch_name: "{{ new_device_vswitch }}"
                portgroup_name: "{{ new_device_pg }}"
            - name: "Remove added vSwitch"
              include_tasks: ../../common/esxi_remove_vswitch.yml
              vars:
                vswitch_name: "{{ new_device_vswitch }}"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
