# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for testing cold add and remove NVDIMM device
# on VM and in guest OS the device is recognized and used.
#
- name: nvdimm_cold_add_remove
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ testing_vars_file | default('../../vars/test.yml') }}"
  tasks:
    - block:
        - include_tasks: ../setup/test_setup.yml
          vars:
            skip_test_no_vmtools: false
        # VM should be in power off state when adding NVDIMM device
        # Do cold add testing
        # Do cold remove testing
      rescue:
        - include_tasks: ../../common/test_rescue.yml
