# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get the files in the VMware Tools install ISO mounted path"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: "Get-childitem -path D:\\ -name"

- name: "Set fact of VMware Tools setup file"
  ansible.builtin.set_fact:
    wintools_setup_exe: |-
      {%- if guest_os_ansible_architecture == "64-bit" and 'setup64.exe' in win_powershell_cmd_output.stdout_lines | default([]) -%}setup64.exe
      {%- elif 'setup.exe' in win_powershell_cmd_output.stdout_lines | default([]) -%}setup.exe
      {%- else -%}N/A
      {%- endif -%}

- name: "Check VMware Tools setup and upgrader exe files exist"
  ansible.builtin.assert:
    that:
      - wintools_setup_exe != 'N/A'
      - "'VMwareToolsUpgrader.exe' in win_powershell_cmd_output.stdout_lines | default([])"
    fail_msg: "VMware Tools installation setup file '{{ wintools_setup_exe }}' or 'VMwareToolsUpgrader.exe' not found in D:\\"
    success_msg: "VMware Tools installation setup file '{{ wintools_setup_exe }}' and 'VMwareToolsUpgrader.exe' are in D:\\"

- name: "Set fact of VMware Tools silent install command"
  ansible.builtin.set_fact:
    vmtools_install_cmd: "D:\\{{ wintools_setup_exe }} /s /v ADDLOCAL=ALL /qn REBOOT=R"

# In Windows Server 2012 R2 guest OS, need to set 'become' to run
# VMware Tools install command
- name: "Execute VMware Tools silent install command in guest"
  ansible.windows.win_shell: "{{ vmtools_install_cmd }}"
  delegate_to: "{{ vm_guest_ip }}"
  ignore_errors: true
  become: "{{ 'Windows Server 2012 R2' in guest_os_ansible_distribution }}"
  become_method: runas
  become_user: "{{ 'Administrator' if ('Windows Server 2012 R2' in guest_os_ansible_distribution) else omit }}"
  register: wintools_install_result
  async: 600
  poll: 0
  environment:
    ANSIBLE_WIN_ASYNC_STARTUP_TIMEOUT: 15
- name: "Pause 2 minutes before checking task status"
  ansible.builtin.pause:
    minutes: 2
- name: "Check VMware Tools install task started"
  ansible.builtin.assert:
    that:
      - wintools_install_result is defined
      - wintools_install_result.ansible_job_id is defined
    fail_msg: >-
      The async task of VMware Tools installation in guest OS is not started.
      Task returned message: {{ wintools_install_result.msg | default('') }}.

- name: "Check VMware Tools install task status every 3 seconds"
  ansible.builtin.async_status:
    jid: "{{ wintools_install_result.ansible_job_id }}"
  register: wintools_install_job
  delegate_to: "{{ vm_guest_ip }}"
  until:
    - wintools_install_job.finished is defined
    - wintools_install_job.finished
  retries: 100
  delay: 3
  when:
    - wintools_install_result is defined
    - wintools_install_result.ansible_job_id is defined

- name: "Pause 30 seconds after VMware Tools install"
  ansible.builtin.pause:
    seconds: 30
- name: "Restart guest OS after VMware Tools install"
  include_tasks: ../utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "restart"
