# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# This test case is testing guest OS in-place upgrade.
# Covered scenarios:
# 1. When there is no inbox pvscsi and vmxnet3 drivers in the OS upgraded from,
# boot disk controller is not pvscsi, no vmxnet3 network adapter before upgrade.
# 2. When there is inbox pvscsi and vmxnet3 drivers in the OS upgraded from,
# boot disk controller is pvscsi, vmxnet3 network adatper also in the VM before upgrade.
#
- name: guest_os_inplace_upgrade
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ testing_vars_file | default('../../vars/test.yml') }}"
  tasks:
    - name: "Test case block"
      block:
        # We only test VMware Tools installed scenario before OS upgrading
        - name: "Execute test setup tasks"
          include_tasks: ../setup/test_setup.yml
          vars:
            skip_test_no_vmtools: true

        - name: "Create current test case log folder"
          include_tasks: ../../common/create_directory.yml
          vars:
            dir_path: "{{ current_test_log_folder }}"
            dir_mode: "0777"

        - name: "Check configured OS installation ISO image existence"
          include_tasks: ../../common/esxi_check_delete_datastore_file.yml
          vars:
            file_in_datastore: "{{ os_installation_iso_upgrade.split(']')[0].strip('[]') }}"
            file_in_datastore_path: "{{ os_installation_iso_upgrade.split(']')[1].strip(' ') }}"
            file_in_datastore_ops: "file"
            file_in_datastore_ops_timeout: 600
            file_in_datastore_failed_ignore: true
          when:
            - os_installation_iso_upgrade is defined
            - os_installation_iso_upgrade

        # Parameter os_installation_iso_upgrade is required
        - name: "Check upgrade to OS installation ISO Image"
          block:
            - name: "Set failure message"
              ansible.builtin.set_fact:
                failure_msg: "Skip test case due to required parameter 'os_installation_iso_upgrade' is not set or empty: '{{ os_installation_iso_upgrade | default('') }}'."
              when: >
                (os_installation_iso_upgrade is undefined) or
                (os_installation_iso_upgrade == "")
            - name: "Set failure message"
              ansible.builtin.set_fact:
                failure_msg: "Skip test case due to parameter 'os_installation_iso_upgrade' set file path does not exist: '{{ file_in_datastore_result | default('Fail') }}'."
              when: >
                (file_in_datastore_result is undefined) or
                (file_in_datastore_result == 'Fail')
            - name: "Test case is blocked"
              include_tasks: ../../common/skip_test_case.yml
              vars:
                skip_msg: "{{ failure_msg }}'"
                skip_reason: "Blocked"
          when: >
            (os_installation_iso_upgrade is undefined or os_installation_iso_upgrade == "") or
            (file_in_datastore_result is undefined or file_in_datastore_result == 'Fail')

        - name: "Get PVSCSI and VMXNET3 driver info before OS upgrade"
          include_tasks: ../wintools_uninstall_verify/get_pvscsi_vmxnet3_info.yml
        - name: "Mount upgrade to ISO image"
          include_tasks: mount_upgrade_to_iso.yml
        - name: "Do in-place upgrade in guest OS"
          include_tasks: execute_upgrade_gos.yml
        - name: "Check OS upgrade"
          include_tasks: check_after_gos_upgrade.yml
        - name: "Reset base snapshot"
          include_tasks: ../../common/reset_base_snapshot.yml
      rescue:
        - name: "Execute tasks when test failed"
          include_tasks: ../../common/test_rescue.yml
      always:
        - name: "Get upgrade log files"
          include_tasks: ../utils/win_get_folder.yml
          vars:
            win_get_folder_src_path: "C:\\upgrade_log"
            win_get_folder_dst_path: "{{ current_test_log_folder }}"
