# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# There is known issue on VMware Tools 12.0.5 and later,
# Please refer to this KB:
# https://kb.vmware.com/s/article/89290
#
- name: "Handle known issue"
  block:
    - name: "Known issue - workaround of incompatible PVSCSI driver issue causing OS upgrade with PVSCSI boot disk failure"
      ansible.builtin.debug:
        msg:
          - "For VMware Tools 12.0.5 and later, the PVSCSI driver installed in the guest (Windows 10) is not compatible with the guest OS (Windows 11) after upgrade, refer to KB https://kb.vmware.com/s/article/89290."
          - "The workaround is deleting incompatible driver and install the compatible driver, then perform OS upgrade."
      tags:
        - known_issue
  when:
    - "'Windows 10' in guest_os_ansible_distribution"
    - vmtools_version is defined
    - vmtools_version is version('12.0.5', '>=')
    - win_pvscsi_before.DriverVersion is defined
    - win_pvscsi_before.DriverVersion is version('1.3.25.0', '>=')
    - vm_has_pvscsi_boot_disk
