# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Check configured VM CPU socket, for Windows 10 client, max socket limit is 2 on ESXi
# versions < 7.0.2. On ESXi 7.0.2 release, the max socket is changed to 4 for Windows
# 10 32bit and 64bit VM.
# The default CPU number of Windows VM is 2, cores per socket is 2.
#
- name: "Set fact of the maximum CPU socket for Windows 10"
  ansible.builtin.set_fact:
    max_socket: "{{ 4 if esxi_version is version('7.0.2', '>=') else 2 }}"

- name: "Check CPU cores per socket and socket"
  ansible.builtin.assert:
    that:
      - cpu_number | int / cpu_cores_per_socket | int in range(1, (max_socket | int + 1))
    fail_msg: "VM guest_id is '{{ guest_id }}', maximum socket is '{{ max_socket }}', invalid configuration CPU number: {{ cpu_number }}, cores: {{ cpu_cores_per_socket }}"
  when: guest_id == "Windows9Guest" or guest_id == "Windows9_64Guest"

- name: "Print the VM CPU number and cores per socket number"
  ansible.builtin.debug:
    msg: "VM CPU number is: {{ cpu_number }}, cores per socket number is: {{ cpu_cores_per_socket }}"
