# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# This task is used for generating ISO file containing OS unattend auto install
# configure file, and/or VMware PVSCSI driver from the downloaded VMware tools
# installation package, and script for configuring Windows for Ansible from this path:
# https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1
#
- name: "Download Ansible remote config script"
  include_tasks: get_ansible_remote_config.yml

- name: "Generate Autounattend install file"
  include_tasks: gen_unattend_xml_file.yml

- name: "Set fact of the file list contained in generated ISO file"
  ansible.builtin.set_fact:
    unattend_install_file_list:
      - "{{ created_unattend_file }}"
      - "{{ local_cache }}/{{ config_remote_windows.split('/')[-1] }}"

- name: "Handle PVSCSI boot disk controller situation"
  block:
    - name: "Get PVSCSI driver files"
      include_tasks: get_pvscsi_driver.yml
    - name: "Add PVSCSI driver files to unattend install file list"
      ansible.builtin.set_fact:
        unattend_install_file_list: "{{ unattend_install_file_list + pvscsi_file_path_list }}"
  when:
    - boot_disk_controller is defined
    - boot_disk_controller == 'paravirtual'
    - windows_has_inbox_driver is undefined or not windows_has_inbox_driver

- name: "Create Autounattend ISO file"
  include_tasks: ../../common/create_iso.yml
  vars:
    create_iso_src: "{{ unattend_install_file_list }}"
    create_iso_dest: "{{ local_cache }}/{{ unattend_install_iso }}"
