# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# This task is used for getting VMware PVSCSI driver from the
# downloaded VMware Tools installation package from this path:
# https://packages.vmware.com/tools/releases/latest/windows
# Notes:
# 2022-05-26, change to use VMware Tools 11.3.5 due to there are
# some changes from VMware Tools 12.0.0 for pvscsi driver.
#
- name: "Set fact of the guest OS bitness"
  ansible.builtin.set_fact:
    win_vmtools_bit: "{{ 'amd64' if guest_id is search('64') else 'i386' }}"

- name: "Set fact of the VMware Tools download URL"
  ansible.builtin.set_fact:
    download_vmtools_url: "https://packages.vmware.com/tools/releases/11.3.5/windows/VMware-tools-windows-11.3.5-18557794.iso"

- name: "Download VMware Tools ISO file from URL"
  include_tasks: download_vmtools_iso.yml

- name: "Extract VMware Tools ISO file to get PVSCSI driver"
  community.general.iso_extract:
    image: "{{ download_vmtools_iso_path }}"
    dest: "{{ local_cache }}/"
    files:
      - "Program Files/VMware/VMware Tools/Drivers/pvscsi/Win8/{{ win_vmtools_bit }}/pvscsi.cat"
      - "Program Files/VMware/VMware Tools/Drivers/pvscsi/Win8/{{ win_vmtools_bit }}/pvscsi.inf"
      - "Program Files/VMware/VMware Tools/Drivers/pvscsi/Win8/{{ win_vmtools_bit }}/pvscsi.sys"
      - "Program Files/VMware/VMware Tools/Drivers/pvscsi/Win8/{{ win_vmtools_bit }}/txtsetup.oem"
  register: vmtools_iso_extract

- name: "Display the VMware Tools ISO file extract result"
  ansible.builtin.debug: var=vmtools_iso_extract
  when: enable_debug

- name: "Set facts of the file paths of PVSCSI driver on local machine"
  ansible.builtin.set_fact:
    pvscsi_file_path_list:
      - "{{ local_cache }}/pvscsi.cat"
      - "{{ local_cache }}/pvscsi.inf"
      - "{{ local_cache }}/pvscsi.sys"
      - "{{ local_cache }}/txtsetup.oem"

- name: "Print the file paths of PVSCSI driver"
  ansible.builtin.debug: var=pvscsi_file_path_list
