- name: "Not cleanup old snapshot by default"
  ansible.builtin.set_fact:
    cleanup_old_snapshots: false
  when: cleanup_old_snapshots is undefined

- name: "Revert and cleanup existing snapshots on existing VM if required"
  include_tasks: ../common/vm_cleanup_snapshot.yml
  when: cleanup_old_snapshots | bool

- name: "Get existing VM info"
  include_tasks: ../common/vm_get_vm_info.yml

- name: "Get VM's power state"
  include_tasks: ../common/vm_get_power_state.yml

- name: "Power on VM"
  include_tasks: ../common/vm_set_power_state.yml
  vars:
    vm_power_state_set: "powered-on"
  when: vm_power_state_get == "poweredOff"

- name: "Wait for VM primary network adapter has MAC address"
  include_tasks: ../common/vm_wait_primary_nic_mac.yml
