# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# This test case is testing deploy Azure IoT Edge for Linux on
# Windows (EFLOW) virtual machine in Windows VM on vSphere.
#
- name: eflow_deploy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              Skip test case '{{ ansible_play_name }}' because nested virtualization is not supported
              on ESXi on ARM.
            skip_reason: "Not Supported"
          when: esxi_cpu_vendor == 'arm'

        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml
          vars:
            create_current_test_folder: true

        - name: "Skip test case for not supported OS '{{ guest_os_ansible_architecture }}'"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to Hyper-V compatible hardware is 64bit processor, this guest OS is: {{ guest_os_ansible_architecture }}."
            skip_reason: "Not Supported"
          when: guest_os_ansible_architecture == "32-bit"

        - name: "Skip test case for not supported OS edition '{{ guest_os_edition }}'"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to EFLOW supported OS edition is 'Pro' or 'Enterprise', this guest OS is: {{ guest_os_edition }}."
            skip_reason: "Not Supported"
          when:
            - guest_os_edition | lower not in ['pro', 'enterprise']
            - guest_os_product_type == 'client'

        - name: "Skip test case for not supported OS '{{ guest_os_ansible_distribution_major_ver }} {{ guest_os_build_num }}'"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg:
              - "Skip test case due to EFLOW supported version is 'Windows 10/Windows Server 2019 minimum build 17763 with all current cumulative updates installed' and 'Windows 11/Windows Server 2022'."
              - "This guest OS major version: {{ guest_os_ansible_distribution_major_ver }}, build number: {{ guest_os_build_num }}."
            skip_reason: "Not Supported"
          when: >
            (guest_os_ansible_distribution_major_ver | int == 10 and guest_os_build_num | int < 17763) or
            (guest_os_ansible_distribution_major_ver | int < 10)

        - name: "Deploy EFLOW VM"
          include_tasks: deploy_eflow_vm.yml
        - name: "Check EFLOW VM"
          include_tasks: check_eflow_vm.yml
        - name: "EFLOW VM stop and start test"
          include_tasks: stop_start_eflow_vm.yml
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
