# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# This test case is testing deploy Azure IoT Edge for Linux on
# Windows (EFLOW) virtual machine in Windows VM on vSphere.
#
- name: eflow_deploy
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ testing_vars_file | default('../../vars/test.yml') }}"
  tasks:
    - name: "Test case block"
      block:
        - include_tasks: ../setup/test_setup.yml
          vars:
            skip_test_no_vmtools: false
       
        - include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to VM is not 64 bit: {{ guest_os_ansible_architecture | default('NA') }}"
            skip_reason: "Not Applicable"
          when: guest_os_ansible_architecture is undefined or guest_os_ansible_architecture != "64-bit"
 
        - include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to Windows edition is not Pro or Enterprise: {{ vm_firmware | default('NA') }}"
            skip_reason: "Not Supported"
          when: >
            (guest_os_ansible_distribution_major_ver is defined and guest_os_ansible_distribution_major_ver | int == 10 and guest_os_build_num is defined and guest_os_build_num | int < 17763) or
            (guest_os_ansible_distribution_major_ver is defined and guest_os_ansible_distribution_major_ver | int < 10)

        - include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to Windows edition is not Pro or Enterprise: {{ vm_firmware | default('NA') }}"
            skip_reason: "Not Supported"
          when: vm_firmware is undefined or vm_firmware | lower != 'efi'
 
        - include_tasks: vbs_enable_test.yml
        - include_tasks: vbs_disable_test.yml
      rescue:
        - include_tasks: ../../common/test_rescue.yml
