# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Initialize the facts of Windows guest OS"
  ansible.builtin.set_fact:
    guest_os_build_num: ''
    guest_os_with_inbox_drivers: false
    vm_guest_os_distribution: ''
    guest_os_edition: ''

- include_tasks: ../../common/get_guest_system_info.yml

- name: "Set guest OS product type to client"
  ansible.builtin.set_fact:
    guest_os_product_type: 'client'
  when: guest_os_product_type | lower == 'workstation'

- name: "Set fact of guest OS build number"
  ansible.builtin.set_fact:
    guest_os_build_num: "{{ guest_os_ansible_distribution_ver.split('.')[2] }}"
  when:
    - guest_os_ansible_distribution_ver
    - guest_os_ansible_distribution_ver.split('.') | length > 2

- name: "Set fact of Windows build with inbox drivers"
  ansible.builtin.set_fact:
    guest_os_with_inbox_drivers: true
  when:
    - guest_os_ansible_distribution_major_ver | int >= 10
    - (guest_os_product_type | lower == 'server' and guest_os_build_num | int >= 20348) or (guest_os_product_type | lower == 'client' and guest_os_build_num | int >= 22449)

- name: "Set fact of Windows guest OS edition"
  ansible.builtin.set_fact:
    guest_os_edition: "{{ guest_os_ansible_distribution.split(' ')[-1] }}"
  when: guest_os_ansible_distribution

- name: "Print Windows guest OS information"
  ansible.builtin.debug:
    msg:
      - "Guest OS: {{ guest_os_ansible_distribution }}"
      - "Guest OS type: {{ guest_os_ansible_system }}"
      - "Guest OS arch: {{ guest_os_ansible_architecture }}"
      - "Guest OS major version: {{ guest_os_ansible_distribution_major_ver }}"
      - "Guest OS minor version: {{ guest_os_ansible_distribution_minor_ver }}"
      - "Guest OS version: {{ guest_os_ansible_distribution_ver }}"
      - "Guest OS kernel: {{ guest_os_ansible_kernel }}"
      - "Guest OS release: {{ guest_os_ansible_distribution_release }}"
      - "Guest OS family: {{ guest_os_family }}"
      - "Guest OS product type: {{ guest_os_product_type }}"
      - "Guest OS build number: {{ guest_os_build_num }}"
      - "Guest OS edition: {{ guest_os_edition }}"
      - "Guest OS should contain inbox drivers: {{ guest_os_with_inbox_drivers }}"

- name: "Set fact of VM guest OS type"
  ansible.builtin.set_fact:
    vm_guest_os_distribution: "{{ guest_os_ansible_distribution }} {{ guest_os_ansible_distribution_ver }} {{ guest_os_ansible_architecture }}"

- name: "Check required facts of Windows guest OS information"
  ansible.builtin.assert:
    that:
      - guest_os_ansible_distribution
      - guest_os_ansible_architecture
      - guest_os_ansible_distribution_major_ver
      - guest_os_ansible_distribution_ver
      - guest_os_product_type
      - guest_os_build_num
      - guest_os_edition
    fail_msg:
      - "Below Windows guest OS information is empty, which must be retrieved and will be used:"
      - "Guest OS: {{ guest_os_ansible_distribution }}"
      - "Guest OS arch: {{ guest_os_ansible_architecture }}"
      - "Guest OS major version: {{ guest_os_ansible_distribution_major_ver }}"
      - "Guest OS version: {{ guest_os_ansible_distribution_ver }}"
      - "Guest OS product type: {{ guest_os_product_type }}"
      - "Guest OS build number: {{ guest_os_build_num }}"
      - "Guest OS edition: {{ guest_os_edition }}"

- name: "Set fact that ansible system information about guest OS has been retrieved"
  ansible.builtin.set_fact:
    guest_os_system_info_retrieved: true
