# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get specified Ethernet IP addresses in Windows guest OS.
# Parameters:
#   ethernet_name: the specified Ethernet name.
#
- name: "Initialize the Ethernet IP address list"
  ansible.builtin.set_fact:
    ethernet_ip: []

- name: "Get '{{ ethernet_name }}' IP addresses in guest OS"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "Get-NetIPAddress | where-object {$_.InterfaceAlias -match '{{ ethernet_name }}'} | foreach {$_.IPAddress}"

- name: "Set fact of '{{ ethernet_name }}' IP addresses"
  when:
    - win_powershell_cmd_output.stdout_lines is defined
    - win_powershell_cmd_output.stdout_lines | length != 0
  block:
    - name: "Set fact of the IP addresses list"
      ansible.builtin.set_fact:
        ethernet_ip: "{{ ethernet_ip | union([item.split('%')[0]]) }}"
      loop: "{{ win_powershell_cmd_output.stdout_lines }}"
    - name: "Add the Ethernet name and IP addresses to dict"
      ansible.builtin.set_fact:
        ethernet_ip_dict: "{{ ethernet_ip_dict | default({}) | combine({ethernet_name: ethernet_ip}) }}"

- name: "Print '{{ ethernet_name }}' IP addresses"
  ansible.builtin.debug: var=ethernet_ip
