# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get TPM device info in Windows guest OS
# Return:
#   win_tpm_info: the dict of TPM device info
#
- name: "Initialize the TPM device status dict"
  ansible.builtin.set_fact:
    win_tpm_info: {}

- name: "Get TPM device info"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "Get-Tpm | fl"
    win_execute_cmd_ignore_error: true

- name: "Set TPM device info dict"
  ansible.builtin.set_fact:
    win_tpm_info: "{{ win_powershell_cmd_output.stdout | replace('\u0000', '') | from_yaml }}"
  when:
    - win_powershell_cmd_output.failed is defined
    - not win_powershell_cmd_output.failed
    - win_powershell_cmd_output.stdout is defined
    - win_powershell_cmd_output.stdout

- name: "Display the TPM device info got in guest OS"
  ansible.builtin.debug: var=win_tpm_info
