# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get Ethernet name with the specified MAC address in Windows guest OS.
# Parameters:
#   win_get_ethernet_name_mac: the MAC address of network adapter to get
#     Ethernet name.
# Return:
#   win_get_ethernet_name: the Ethernet name of the network adapter with
#     specified MAC address.
#
- name: "Initialize the Ethernet name"
  ansible.builtin.set_fact:
    win_get_ethernet_name: ''

- name: "Get Ethernet name of the network adapter with specified MAC address"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "(Get-NetAdapter | where-object {$_.MacAddress -eq '{{ win_get_ethernet_name_mac | replace(':','-') }}'}).Name"
    win_execute_cmd_ignore_error: true

- name: "Check PowerShell command result"
  ansible.builtin.assert:
    that:
      - win_powershell_cmd_output.rc is defined
      - win_powershell_cmd_output.rc == 0
      - win_powershell_cmd_output.stdout_lines is defined
      - win_powershell_cmd_output.stdout_lines | length != 0
    fail_msg: "Failed to get Ethernet name with specified MAC address: {{ win_get_ethernet_name_mac }}"

- name: "Set fact of the Ethernet name"
  ansible.builtin.set_fact:
    win_get_ethernet_name: "{{ win_powershell_cmd_output.stdout_lines[0] }}"

- name: "Print the Ethernet name of network adapter with MAC address '{{ win_get_ethernet_name_mac }}'"
  ansible.builtin.debug: var=win_get_ethernet_name
