# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Install Windows online updates in specified categories, skip optional
# ones or in a reject list in Windows guest OS.
# Parameters:
#   win_updates_categories (optional): A list of categories to install updates from.
#     Some possible categories are: Application, Connectors, Critical Updates,
#     Definition Updates, Developer Kits, Feature Packs, Guidance, Security Updates,
#     Service Packs, Tools, Update Rollups, Updates and Upgrades.
#     Default value is '*', which matches all categories.
#   win_updates_reject_list (optional): A list of update titles or KB numbers that
#     can be used to specify which updates are to be excluded from installation.
#   win_updates_ignore_errors (optional): Whether to ignore errors when installing
#     Windows updates. Default is false.
#   win_updates_log_file (optional): The log file path for Windows Update in guest OS.
#     Default is 'C:\win_updates_log.txt'.
# Return:
#   win_online_updates_installed: Indicates if there are Windows online updates
#     installed in guest OS.
#
- name: "Set fact and initialize Windows online updates install parameters"
  ansible.builtin.set_fact:
    win_updates_log_file: "{{ win_updates_log_file | default('C:\\win_updates_log.txt') }}"
    win_online_updates_installed: false

- name: "Install Windows online updates"
  ansible.windows.win_updates:
    server_selection: "windows_update"
    category_names: "{{ win_updates_categories | default('*') }}"
    reject_list: "{{ win_updates_reject_list | default('') }}"
    log_path: "{{ win_updates_log_file }}"
    skip_optional: true
    state: "installed"
    reboot: true
    reboot_timeout: 2700
  delegate_to: "{{ vm_guest_ip }}"
  register: win_updates_install_result
  ignore_errors: "{{ win_updates_ignore_errors | default(false) }}"

- name: "Print Windows online updates install result"
  debug: var=win_updates_install_result
  when: enable_debug

- name: "Set fact of Windows online updates install status"
  ansible.builtin.set_fact:
    win_online_updates_installed: true
  when:
    - win_updates_install_result.found_update_count is defined
    - win_updates_install_result.found_update_count | int != 0
    - win_updates_install_result.installed_update_count is defined
    - win_updates_install_result.found_update_count | int == win_updates_install_result.installed_update_count | int

- name: "Display Windows online updates install status"
  ansible.builtin.debug: var=win_online_updates_installed
