# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Decrypt the BitLocker encrypted volumes
# Parameters:
#   decrypt_wait_time: the time in seconds to wait for the volume decryption.
#
- name: "Get encrypted volumes in guest OS"
  include_tasks: win_get_bitlocker_volume.yml

- name: "Decrypt the BitLocker volumes"
  when:  bitlocker_volume_list | length > 0
  block:
    - name: "Initialize the decryption wait time"
      ansible.builtin.set_fact:
        decrypt_wait_time: 900
      when: decrypt_wait_time is undefined or not decrypt_wait_time

    - name: "Decrypt the BitLocker volumes"
      ansible.windows.win_shell: >-
        $BLV = Get-BitLockerVolume;
        Disable-BitLocker -MountPoint $BLV
      register: decrypt_volume_cmd_result
      delegate_to: "{{ vm_guest_ip }}"
      ignore_errors: true
      until:
        - decrypt_volume_cmd_result.stderr_lines is defined
        - decrypt_volume_cmd_result.stderr_lines | length == 0
      retries: 3
      delay: 120

    - name: "Check if decrypt command succeeds"
      ansible.builtin.assert:
        that:
          - decrypt_volume_cmd_result.stderr_lines is defined
          - decrypt_volume_cmd_result.stderr_lines | length == 0
        fail_msg: >-
          Disable bitlocker volume failed. The returned error message of the command,
          stderr - {{ decrypt_volume_cmd_result.stderr_lines | default('') }},
          msg - {{ decrypt_volume_cmd_result.msg | default('') }}.

    - name: "Check if Decryption is completed"
      ansible.windows.win_shell: "(Get-BitLockerVolume | Where-Object { $_.EncryptionPercentage -GT 0 } | measure).Count"
      register: decrypt_volume_result
      delegate_to: "{{ vm_guest_ip }}"
      ignore_errors: true
      until:
        - decrypt_volume_result.stdout_lines is defined
        - decrypt_volume_result.stdout_lines | length != 0
        - decrypt_volume_result.stdout_lines[0] | int == 0
      retries: "{{ (decrypt_wait_time | int / 60) | int }}"
      delay: 60

    - name: "Volume decryption failed"
      ansible.builtin.fail:
        msg: "Failed to decrypt the OS volumes in {{ decrypt_wait_time }} seconds."
      when:
        - decrypt_volume_result.failed is defined
        - decrypt_volume_result.failed
