# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get PVSCSI driver installer info in Windows guest OS
- name: "Initialize the installer info of PVSCSI driver"
  ansible.builtin.set_fact:
    win_pvscsi_installer: []

- include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "Get-ItemPropertyValue -Path 'HKLM:\\System\\CurrentControlSet\\Services\\pvscsi' -Name 'vwdk.installers'"
- name: "Set fact of the installer info of PVSCSI driver"
  ansible.builtin.set_fact:
    win_pvscsi_installer: "{{ win_powershell_cmd_output.stdout_lines | select }}"
  when:
    - win_powershell_cmd_output.stdout_lines is defined
    - win_powershell_cmd_output.stdout_lines | length != 0

- name: "Display the installer info of PVSCSI driver"
  ansible.builtin.debug:
    msg: "Get the installer info of PVSCSI driver in guest OS: {{ win_pvscsi_installer }}"
