# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get Ethernet IP address info dict in Windows guest OS
- name: "Initialize Ethernet name list and Ethernet IP dict"
  ansible.builtin.set_fact:
    ethernet_name_list: []
    ethernet_ip_dict: {}

- name: "Get Ethernet name list in Windows guest OS"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "(Get-NetAdapter | where-object {$_.Name -notmatch 'vEthernet'}).Name"

- name: "Set fact of the Ethernet name list"
  ansible.builtin.set_fact:
    ethernet_name_list: "{{ win_powershell_cmd_output.stdout_lines }}"
  when:
    - win_powershell_cmd_output.stdout_lines is defined
    - win_powershell_cmd_output.stdout_lines | length != 0

- name: "Get IP addresses of each Ethernet"
  include_tasks: win_get_ethernet_ip.yml
  with_items: "{{ ethernet_name_list }}"
  loop_control:
    loop_var: ethernet_name
  when: ethernet_name_list | length != 0

- name: "Print the Ethernet name list and Ethernet IP dict"
  ansible.builtin.debug:
    msg:
      - "Get Ethernet names in guest OS: {{ ethernet_name_list }}"
      - "Get Ethernet IP address dict in guest OS: {{ ethernet_ip_dict | to_yaml }}"
