# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get the total number of disks in Windows guest
- name: "Initialize the total number of disks"
  ansible.builtin.set_fact:
    disk_num_guest: 0

- name: "Get the total number of disks in guest OS"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "(Get-Disk | measure).Count"
    win_execute_cmd_ignore_error: true

- name: "Set fact of total number of disks in guest OS"
  ansible.builtin.set_fact:
    disk_num_guest: "{{ win_powershell_cmd_output.stdout_lines[0] }}"
  when:
    - not win_powershell_cmd_output.failed | default(false)
    - win_powershell_cmd_output.stdout_lines is defined
    - win_powershell_cmd_output.stdout_lines | length == 1

- name: "Display the total number of disks in guest OS"
  ansible.builtin.debug:
    msg: "Get the total number of disks in guest OS: {{ disk_num_guest }}"
