# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Remove specified installed Appx package in Windows guest OS
# Parameters:
#   win_appx_package: the keyword in the fullname of Appx package.
#   win_remove_appx_ignore_errors (optional): whether to ignore errors
#     when getting and removing specified Appx packages. Default is false.
#
- name: "Check required parameter"
  ansible.builtin.assert:
    that:
      - win_appx_package is defined
      - win_appx_package
    fail_msg: "Parameter 'win_appx_package' is required to be set to a keyword of Appx package's fullname."

- name: "Initialize the list of installed Appx packages"
  ansible.builtin.set_fact:
    win_appx_packages_list: []

- name: "Get installed Appx packages with keyword in the fullname"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "(Get-AppxPackage -AllUsers -Name '*{{ win_appx_package }}*').PackageFullName"
    win_execute_cmd_ignore_error: "{{ win_remove_appx_ignore_errors | default(false) }}"

- name: "Set fact of the list of installed Appx packages"
  ansible.builtin.set_fact:
    win_appx_packages_list: "{{ win_powershell_cmd_output.stdout_lines | select }}"
  when:
    - win_powershell_cmd_output.stdout_lines is defined
    - win_powershell_cmd_output.stdout_lines | select | length != 0

- name: "Remove Appx packages got with specified keyword"
  when: win_appx_packages_list | length > 0
  block:
    - name: "Remove Appx package {{ item }}"
      include_tasks: win_execute_cmd.yml
      vars:
        win_powershell_cmd: "Remove-AppxPackage -Package {{ item }}"
        win_execute_cmd_ignore_error: "{{ win_remove_appx_ignore_errors | default(false) }}"
      loop: "{{ win_appx_packages_list }}"

- name: "Not get installed Appx package"
  ansible.builtin.debug:
    msg: "Not get installed Appx package with keyword '{{ win_appx_package }}' in the fullname, skip removing task."
  when: win_appx_packages_list | length == 0
