# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get VMXNET3 driver installer info in Windows guest OS
- name: "Initialize the installer of VMXNET3 driver"
  ansible.builtin.set_fact:
    win_vmxnet3_installer: []

- include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "Get-ItemPropertyValue -Path 'HKLM:\\System\\CurrentControlSet\\Services\\vmxnet3ndis6' -Name 'vwdk.installers'"
- name: "Set fact of the installer info of VMXNET3 driver"
  ansible.builtin.set_fact:
    win_vmxnet3_installer: "{{ win_powershell_cmd_output.stdout_lines | select }}"
  when:
    - win_powershell_cmd_output.stdout_lines is defined
    - win_powershell_cmd_output.stdout_lines | length != 0

- name: "Display the installer info VMXNET3 driver"
  ansible.builtin.debug:
    msg: "Get the installer info of VMXNET3  driver in guest OS: {{ win_vmxnet3_installer }}"
