# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get the list of problem devices in Windows guest OS
# This used '/enum-devices' parameter avaialble starting in Windows 10 v1903
#
- name: "Initialize the problem device status"
  ansible.builtin.set_fact:
    gos_has_problem_device: false
    gos_problem_device_list: []

- include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "pnputil /enum-devices /problem"
  when:
    - guest_os_ansible_distribution_major_ver is defined
    - guest_os_ansible_distribution_major_ver | int >= 10
    - guest_os_build_num is defined
    - guest_os_build_num | int >= 18362

- name: "Get problem devices in guest OS"
  ansible.builtin.set_fact:
    gos_has_problem_device: true
    gos_problem_device_list: "{{ win_powershell_cmd_output.stdout_lines }}"
  when:
    - win_powershell_cmd_output.stdout_lines | length > 1
    - "'No devices were found' not in win_powershell_cmd_output.stdout"
