# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Disable Windows auto update and pause Windows Update 7 days,
# or delete this pauing Windows Update config in registry to
# resume Windows Update.
# Paramters:
#   win_update_ops: valid values are 'pause' or 'resume'.
#
- name: "Check required parameter"
  ansible.builtin.assert:
    that:
      - win_update_ops is defined
      - win_update_ops in ['pause', 'resume']
    fail_msg: >-
      Parameter 'win_update_ops': {{ win_update_ops | default('') }} is not set correctly,
      valid value is 'pause' or 'resume'.

- name: "Set fact of the PowerShell script name"
  ansible.builtin.set_fact:
    win_update_script: "{{ win_update_ops }}_windows_update.ps1"

- name: "Set fact of the PowerShell script local and remote paths"
  ansible.builtin.set_fact:
    local_ps_file: "scripts/{{ win_update_script }}"
    remote_ps_file: "C:\\{{ win_update_script }}"

- name: "Copy PowerShell script from local to guest OS"
  include_tasks: win_copy_file_from_local.yml
  vars:
    src_path_local: "{{ local_ps_file }}"
    dest_path_remote: "C:\\"

- name: "Get PowerShell script existence state in guest OS"
  include_tasks: win_check_file_exist.yml
  vars:
    win_check_file_exist_file: "{{ remote_ps_file }}"
- name: "Make sure PowerShell script exists in guest OS"
  ansible.builtin.assert:
    that:
      - win_check_file_exist_result
    fail_msg: "PowerShell script is not found in guest OS in this path: {{ remote_ps_file }}"

# Pause Windows Update is not a demand task, so ignore errors
- name: "Execute {{ win_update_ops }} Windows Update PowerShell script in guest OS"
  ansible.windows.win_command: "powershell.exe -ExecutionPolicy bypass -File {{ remote_ps_file }}"
  delegate_to: "{{ vm_guest_ip }}"
  ignore_errors: "{{ win_update_ops == 'pause' }}"
  register: win_update_ops_result
- name: "Display the PowerShell script execute result"
  ansible.builtin.debug: var=win_update_ops_result
  when: enable_debug
