# Copyright 2022-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get the specified driver info in the Windows guest OS that is
# currently running.
# Parameters:
#   win_driver_inf: the .inf file of the driver you want detailed
#   information about.
#
- name: "Check required parameter"
  ansible.builtin.assert:
    that:
      - win_driver_inf is defined
      - win_driver_inf
    fail_msg: "Parameter 'win_driver_inf' must be set to the driver inf file name."

- name: "Initialize driver info"
  ansible.builtin.set_fact:
    win_driver_info: []

- name: "Get driver info in guest OS"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: >-
      (Get-WindowsDriver -Online -Driver '{{ win_driver_inf }}')[0] | 
      select Driver, Date, Version, Inbox, ManufacturerName, OriginalFileName, BootCritical, ClassName
    win_execute_cmd_ignore_error: true

- name: "Set fact of the driver info"
  ansible.builtin.set_fact:
    win_driver_info: "{{ win_powershell_cmd_output.stdout_lines }}"
  when:
    - win_powershell_cmd_output.rc is defined
    - win_powershell_cmd_output.rc == 0

- name: "Print the driver info"
  ansible.builtin.debug: var=win_driver_info
