# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Install all available Windows Updates in Windows guest OS
#
- name: "Set fact of Windows Updates install log path"
  ansible.builtin.set_fact:
    win_udpates_log_file: "C:\\win_updates_log.txt"

- name: "Get the list of Windows Updates"
  ansible.windows.win_updates:
    server_selection: "windows_update"
    category_names: '*'
    log_path: "{{ win_udpates_log_file }}"
    skip_optional: true
    state: "searched"
  delegate_to: "{{ vm_guest_ip }}"
  register: win_updates_list
- name: "Print the list of Windows Updates"
  ansible.builtin.debug: var=win_updates_list

- name: "Install above listed Windows Updates"
  when:
    - win_updates_list.found_update_count is defined
    - win_updates_list.found_update_count | int != 0
    - win_updates_list.updates is defined
    - win_updates_list.updates | length != 0
  block:
    - name: "Install Windows Updates"
      ansible.windows.win_updates:
        server_selection: "windows_update"
        category_names: '*'
        log_path: "{{ win_udpates_log_file }}"
        skip_optional: true
        state: "installed"
        reboot: true
        reboot_timeout: 1800
      delegate_to: "{{ vm_guest_ip }}"
      register: win_updates_install_result
    - name: "Print Windows Updates install result"
      debug: var=win_updates_install_result

- name: "Skip install Windows Updates"
  ansible.builtin.debug:
    msg: "Will not execute Windows Updates installation task due to no Windows Updates listed."
  when: >
    (win_updates_list.found_update_count is undefined) or
    (win_updates_list.found_update_count | int == 0)
