# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Enable Hyper-V feature in Windows guest OS.
# Parameters:
#   win_product_type: 'client' or 'server'.
#
- name: "Check required parameter"
  ansible.builtin.assert:
    that:
      - win_product_type is defined
      - win_product_type | lower in ['client', 'server']
    fail_msg: "Parameter 'win_product_type' is required and set to 'client' or 'server'."

- name: "Set fact of Hyper-V powershell commands for Windows Client"
  ansible.builtin.set_fact:
    win_enable_hyperv_cmd: "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All"
    win_check_hyperv_cmd: "(Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V).State"
  when: win_product_type | lower == 'client'

- name: "Set fact of Hyper-V powershell commands for Windows Server"
  ansible.builtin.set_fact:
    win_enable_hyperv_cmd: "Install-WindowsFeature -Name Hyper-V -IncludeManagementTools"
    win_check_hyperv_cmd: "(Get-WindowsFeature Hyper-V).InstallState"
  when: win_product_type | lower == 'server'

- name: "Execute enable Hyper-V command in guest OS"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "{{ win_enable_hyperv_cmd }}"

- name: "Wait 10 seconds before restart guest OS"
  ansible.builtin.pause:
    seconds: 10
- name: "Restart guest OS after enable Hyper-V"
  include_tasks: win_shutdown_restart.yml
  vars:
    set_win_power_state: "restart"

- name: "Get Hyper-V feature state in guest OS"
  include_tasks: win_execute_cmd.yml
  vars:
    win_powershell_cmd: "{{ win_check_hyperv_cmd }}"
- name: "Check Hyper-V feature installed in guest OS"
  ansible.builtin.assert:
    that:
      - win_powershell_cmd_output.stdout_lines is defined
      - win_powershell_cmd_output.stdout_lines | length == 1
      - win_powershell_cmd_output.stdout_lines[0].strip() in ['Installed', 'Enabled']
    fail_msg: "Hyper-V feature state in guest OS is not 'Installed' or 'Enabled': '{{ win_powershell_cmd_output.stdout_lines | default('') }}'"
