# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Check vTPM device status in guest OS
- name: "Make sure TPM device is present and ready"
  ansible.builtin.assert:
    that:
      - win_tpm_info['TpmPresent'] | bool
      - win_tpm_info['TpmReady'] | bool
      - win_tpm_info['ManufacturerIdTxt'] | trim == 'VMW'
    fail_msg: "TPM device status is not present or ready, or manufacturer ID is not 'VMW' in guest OS: {{ win_tpm_info }}."

- name: "Make sure TPM device is enabled and activated"
  ansible.builtin.assert:
    that:
      - win_tpm_info['TpmEnabled'] | bool
      - win_tpm_info['TpmActivated'] | bool
    fail_msg: "TPM device status is not enabled or activated in guest OS: {{ win_tpm_info }}."
  when: guest_os_ansible_distribution is not search('2016|2019')
