# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Shutdown guest OS before removing vTPM device"
  include_tasks: ../utils/win_shutdown_restart.yml
  vars:
    set_win_power_state: "shutdown"

- name: "Remove vTPM device from VM"
  include_tasks: ../../common/vm_add_remove_vtpm.yml
  vars:
    vtpm_operation: 'absent'
- name: "Pause 10 seconds after removing vTPM device"
  ansible.builtin.pause:
    seconds: 10

- name: "Power on VM after removing vTPM device"
  include_tasks: ../../common/vm_set_power_state.yml
  vars:
    vm_power_state_set: "powered-on"
- name: "Update in-memory inventory after VM power on"
  include_tasks: ../utils/win_update_inventory.yml

# check VM is not encrypted
# power on VM
# check no TPM deive in guest OS
# clear cloned VM
