# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Handle VM without vTPM device"
  block:
    - name: "Power off instant cloned VM"
      include_tasks: ../../common/vm_set_power_state.yml
      vars:
        vm_power_state_set: 'powered-off'
    - name: "Add key provider on vCenter server"
      include_tasks: ../../common/vcenter_add_key_provider.yml
      vars:
        vc_cert_path: "{{ current_test_log_folder }}"
      when:
        - key_provider_type is defined and key_provider_type
        - not (key_provider_added is defined and key_provider_added)

    - name: "Add vTPM device to cloned VM"
      include_tasks: ../../common/vm_add_remove_vtpm.yml
      vars:
        vtpm_operation: 'present'
    - name: "Pause 10 seconds after adding vTPM device"
      ansible.builtin.pause:
        seconds: 10
  when: not device_info_with_label

- name: "Power on cloned VM"
  include_tasks: ../../common/vm_set_power_state.yml
  vars:
    vm_power_state_set: 'powered-on'

- name: "Get cloned VM MAC address"
  include_tasks: ../../common/vm_wait_primary_nic_mac.yml
- name: "Get cloned VM IP address"
  include_tasks: ../../common/vm_get_ip.yml
  vars:
    vm_get_ip_timeout: 600
- name: "Print VM IP address"
  ansible.builtin.debug:
    msg:
      - "Cloned VM IP address: {{ vm_guest_ip }}"
      - "Parent VM IP address: {{ vm_ip_clone_from }}"

- name: "Check Windows winrm is connectable"
  include_tasks: ../utils/win_check_winrm.yml
- name: "Add Windows host to in-memory inventory"
  include_tasks: ../utils/add_windows_host.yml

- name: "Check vTPM device added"
  include_tasks: vtpm_add_remove_check.yml
  vars:
    vtpm_test_operation: "add"
