# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# For Windows Server 2019 VM with SCSI disk, enabling BitLocker in guest OS returns error:
# "Set-BitLockerVolumeInternal : A device attached to the system is not functioning.
# (Exception from HRESULT: 0x8007001F)".
# Here is the workaround for this known issue.
#
- name: "Set fact of VM advanced setting for disabling thin provisioning"
  ansible.builtin.set_fact:
    vm_advanced_settings:
      - key: "disk.disableThinProvisioning"
        value: "TRUE"

- name: "Add 'disk.disableThinProvisioning' in VM's extra config"
  include_tasks: ../utils/win_set_vm_extra_config.yml

- name: "Check 'disk.disableThinProvisioning' is 'TRUE' in VM's extra config after VM power-on"
  ansible.builtin.assert:
    that:
      - vm_extra_config['disk.disableThinProvisioning'] is defined
      - vm_extra_config['disk.disableThinProvisioning'] == 'TRUE'
    fail_msg: >-
      The 'disk.disableThinProvisioning' is not 'TRUE' in VM's extra config after VM power-on. In VM's extra config,
      disk.disableThinProvisioning = {{ vm_extra_config['disk.disableThinProvisioning'] | default('') }}.

- name: "Try to enable BitLocker on 'C:' drive again after workaround"
  include_tasks: ../utils/win_execute_cmd.yml
  vars:
    win_powershell_cmd: "Enable-BitLocker -MountPoint 'C:' -UsedSpaceOnly -TpmProtector -SkipHardwareTest"
