# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Current VM has at least one snapshot, e.g., 'BaseSnapshot',
# adding/removing vTPM device will fail with this message
# "Cannot change encryption state with virtual machine snapshots present.".
# So here clone a new VM without snapshot to do vTPM test.
#
# Check if current VM has vTPM device
- name: "Get vTPM device on current VM"
  include_tasks: ../../common/vm_get_device_with_label.yml
  vars:
    device_label: 'Virtual TPM'
- name: "vTPM device exists"
  ansible.builtin.debug:
    msg: "Current VM has vTPM device already."
  when: device_info_with_label

- name: "Set facts of cloned VM name and save current VM info"
  ansible.builtin.set_fact:
    vm_name_clone_to: "{{ vm_name }}_clone_{{ testrun_timestamp }}"
    vm_name_clone_from: "{{ vm_name }}"
    vm_nic_mac_clone_from: "{{ vm_primary_nic_mac }}"
    vm_ip_clone_from: "{{ vm_guest_ip }}"

# Instant Clone is not supported when VM with vTPM device
- name: "Instant Clone a new VM from current VM"
  include_tasks: ../../common/vm_instant_clone.yml
  vars:
    parent_vm_name: "{{ vm_name }}"
    cloned_vm_name: "{{ vm_name_clone_to }}"
  when: not device_info_with_label

# Clone a new VM when VM with vTPM device
- name: "Clone a new VM from current VM"
  include_tasks: ../../common/vm_clone.yml
  vars:
    parent_vm_name: "{{ vm_name }}"
    cloned_vm_name: "{{ vm_name_clone_to }}"
  when: device_info_with_label

- name: "Switch to cloned VM for testing"
  ansible.builtin.set_fact:
    vm_name: "{{ vm_name_clone_to }}"

- name: "Do cold add vTPM device test"
  include_tasks: cold_add_vtpm.yml

- name: "Do cold remove vTPM device test"
  include_tasks: cold_remove_vtpm.yml

- name: "Power off cloned VM before removing it"
  include_tasks: ../../common/vm_set_power_state.yml
  vars:
    vm_power_state_set: 'powered-off'
- name: "Remove cloned VM"
  include_tasks: ../../common/vm_remove.yml
