# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for checking VM is encrypted when adding
# TPM device to VM, VM is not encrypted after removing TPM device.
#
- name: vtpm_cold_add_remove
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to VM hardware version is: {{ vm_hardware_version_num }}, not >= 14."
            skip_reason: "Not Supported"
          when: vm_hardware_version_num | int < 14

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to VM firmware is: {{ vm_firmware }}, not EFI."
            skip_reason: "Not Applicable"
          when: vm_firmware | lower != 'efi'

        - name: "Cold add and remove VM vTPM device test"
          include_tasks: vtpm_add_remove_test.yml
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
      always:
        - name: "Revert back VM name and VM primary MAC address"
          ansible.builtin.set_fact:
            vm_name: "{{ vm_name_clone_from }}"
            vm_primary_nic_mac: "{{ vm_nic_mac_clone_from }}"
          when:
            - vm_name_clone_from is defined
            - vm_nic_mac_clone_from is defined
