# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for checking VM is encrypted when adding
# TPM device to VM, VM is not encrypted after removing TPM device.
#
- name: vtpm_cold_add_remove
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to VM is not 64 bit: {{ guest_os_ansible_architecture | default('NA') }}"
            skip_reason: "Not Applicable"
          when: guest_os_ansible_architecture != "64-bit"

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Skip test case due to VM firmware is not EFI: {{ vm_firmware | default('NA') }}"
            skip_reason: "Not Applicable"
          when: vm_firmware | lower != 'efi'

        - name: "Cold add VM vTPM device test"
          include_tasks: cold_add_vtpm_test.yml
        - name: "Cold remove VM vTPM device test"
          include_tasks: cold_remove_vtpm_test.yml
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
      always:
        - name: "Revert back VM name and VM primary MAC"
          ansible.builtin.set_fact:
            vm_name: "{{ vm_name_clone_from }}"
            vm_primary_nic_mac: "{{ vm_nic_mac_clone_from }}"
          when:
            - vm_name_clone_from is defined
            - vm_name_clone_from
