# Copyright 2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Current VM has at least one snapshot, e.g., 'BaseSnapshot',
# adding vTPM device to VM will fail with this message "Cannot change
# encryption state with virtual machine snapshots present.".
# So here clone a new VM without snapshot to do vTPM test.
#
- name: "Add key provider on vCenter server"
  include_tasks: ../../common/vcenter_add_key_provider.yml
  vars:
    vc_cert_path: "{{ current_test_log_folder }}"
  when:
    - key_provider_type is defined and key_provider_type
    - not (key_provider_added is defined and key_provider_added)

- name: "Set fact of the name of cloned VM"
  ansible.builtin.set_fact:
    vm_name_clone_to: "{{ vm_name }}_clone_{{ testrun_timestamp }}"

- name: "Clone a new VM from current VM"
  include_tasks: ../../common/vm_instant_clone.yml
  vars:
    parent_vm_name: "{{ vm_name }}"
    cloned_vm_name: "{{ vm_name_clone_to }}"

- name: "Save current VM name and primary NIC MAC address"
  ansible.builtin.set_fact:
    vm_name_clone_from: "{{ vm_name }}"
    vm_nic_mac_clone_from: "{{ vm_primary_nic_mac }}"

- name: "Switch to cloned VM for testing"
  ansible.builtin.set_fact:
    vm_name: "{{ vm_name_clone_to }}"
    test_on_cloned_vm: true

- name: "Add vTPM device to cloned VM"
  include_tasks: ../../common/vm_add_remove_vtpm.yml
  vars:
    vtpm_operation: 'present'
- name: "Pause 10 seconds after adding vTPM device"
  ansible.builtin.pause:
    seconds: 10

- name: "Power on cloned VM"
  include_tasks: ../../common/vm_set_power_state.yml
  vars:
    vm_power_state_set: 'powered-on'

- name: "Get cloned VM MAC address"
  include_tasks: ../../common/vm_wait_primary_nic_mac.yml
- name: "Get cloned VM IP address"
  include_tasks: ../../common/vm_get_ip.yml
  vars:
    vm_get_ip_timeout: 600
- name: "Print cloned VM IP address"
  ansible.builtin.debug:
    msg: "Get cloned VM IP address: {{ vm_guest_ip }}"
- name: "Check Windows winrm is connectable"
  include_tasks: ../utils/win_check_winrm.yml
- name: "Add Windows host to in-memory inventory"
  include_tasks: ../utils/add_windows_host.yml
