# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Add a new vSphere Standard Switch port group on ESXi host.
# Parameters:
#   vswitch_name: The standard switch name which the port group belong to.
#   portgroup_name: The name of port group to be added.
#
- name: "Add port group '{{ portgroup_name }}' on standard switch '{{ vswitch_name }}'"
  community.vmware.vmware_portgroup:
    hostname: "{{ vsphere_host_name }}"
    username: "{{ vsphere_host_user }}"
    password: "{{ vsphere_host_user_password }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    hosts: ["{{ esxi_hostname }}"]
    switch: "{{ vswitch_name | default('vSwitch0') }}"
    portgroup: "{{ portgroup_name }}"
  register: new_portgroup

- name: "Display the result of adding port group"
  ansible.builtin.debug: var=new_portgroup
  when: enable_debug
