# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Remove specified vSphere Standard Switch port group from ESXi host.
# Parameters:
#   vswitch_name: The standard switch name which the port group belong to.
#   portgroup_name: The name of port group to be removed.
#
- name: "Remove port group '{{ portgroup_name }}' on standard switch '{{ vswitch_name }}'"
  community.vmware.vmware_portgroup:
    hostname: "{{ vsphere_host_name }}"
    username: "{{ vsphere_host_user }}"
    password: "{{ vsphere_host_user_password }}"
    validate_certs: "{{ validate_certs | default(false) }}"
    hosts: ["{{ esxi_hostname }}"]
    switch: "{{ vswitch_name | default('vSwitch0') }}"
    portgroup: "{{ portgroup_name }}"
    state: "absent"
  register: removed_portgroup

- name: "Display the result of removing port group"
  ansible.builtin.debug: var=removed_portgroup
  when: enable_debug
