# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Collect guest system info using Ansible setup module
# Parameters:
#   get_gos_info_filter (optional): if the filter is set, getting the filtered
#     guest system info, if not set, will get the whole ansible facts.
#   get_gos_info_timeout (optional): the timeout in seconds for individual
#     fact gathering, default value is 30.
# Return:
#   guest_system_info: the gathered guest system info.
#
- name: "Collect guest system information for VM '{{ vm_guest_ip }}'"
  ansible.builtin.setup:
    filter: "{{ get_gos_info_filter is defined | ternary(get_gos_info_filter, []) }}"
    gather_timeout: "{{ get_gos_info_timeout is defined and get_gos_info_timeout | ternary(get_gos_info_timeout, 30) }}"
  register: get_gos_info_result
  delegate_to: "{{ vm_guest_ip }}"

- name: "Set gathered guest system information"
  ansible.builtin.set_fact:
    guest_system_info: "{{ get_gos_info_result.ansible_facts }}"
