# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Collect guest system info using Ansible setup module
# Parameters:
#   get_gos_info_filter (optional): if supplied, return the facts that match
#     one of the specified pattern in the list. Default value is [], which means
#     returning all the gathered facts.
#   get_gos_info_timeout (optional): the timeout in seconds for individual
#     fact gathering, default value is 30.
# Return:
#   guest_system_info: the gathered guest system info.
#
- name: "Collect guest system information for VM '{{ vm_guest_ip }}'"
  ansible.builtin.setup:
    filter: "{{ get_gos_info_filter | default([]) }}"
    gather_timeout: "{{ get_gos_info_timeout | default(30) }}"
  register: get_gos_info_result
  delegate_to: "{{ vm_guest_ip }}"

- name: "Set gathered guest system information"
  ansible.builtin.set_fact:
    guest_system_info: "{{ get_gos_info_result.ansible_facts }}"
