# Copyright 2025 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Set fact of the new network netmask"
  ansible.builtin.set_fact:
    new_network_netmask: "255.255.255.0"
    new_network_netmask_bits: 24

- name: "Setup network environment for testing on ESXi on X86"
  include_tasks: vss_network_setup.yml
  when:
    - esxi_cpu_vendor == 'arm'
    - vss_network_is_setup is undefined or not vss_network_is_setup

- name: "Setup network environment for testing on ESXi on ARM"
  include_tasks: vds_network_setup.yml
  when:
    - esxi_cpu_vendor != 'arm'
    - vds_network_is_setup is undefined or not vds_network_is_setup
