# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Setup network environment for testing on ESXi on X86"
  include_tasks: vss_network_setup.yml
  when:
    - esxi_cpu_vendor != 'arm'
    - vss_network_is_setup is undefined or not vss_network_is_setup

- name: "Setup network environment for testing on ESXi on ARM"
  when: esxi_cpu_vendor == 'arm'
  block:
    - name: "Setup network environment with vSphere Distributed Switch"
      include_tasks: vds_network_setup.yml
      when:
        - vcenter_is_defined
        - vds_network_is_setup is undefined or not vds_network_is_setup

    - name: "vCenter server info is not set"
      ansible.builtin.fail:
        msg: >-
          Can't setup network environment with vSphere Distributed Switch when vCenter server
          info is not set, please conifgure parameters 'vcenter_hostname', 'vcenter_username'
          and 'vcenter_password' in vars/test.yml.
      when: not vcenter_is_defined
