# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Prepare vSphere Standard Switch network environment"
  include_tasks: vss_network_setup.yml
  when:
    - vss_network_is_setup is undefined or not vss_network_is_setup
    - esxi_cpu_vendor != 'arm'
    - network_testbed_type is undefined or network_testbed_type == 'vss'

- name: "Prepare vSphere Distributed Switch network environment"
  when:
    - vds_network_is_setup is undefined or not vds_network_is_setup
    - esxi_cpu_vendor == 'arm' or (network_testbed_type is defined and network_testbed_type == 'vds')
  block:
    - name: "vCenter server info is not set"
      ansible.builtin.fail:
        msg: >-
          Can't setup network environment with vSphere Distributed Switch when vCenter server
          info is not set, please conifgure parameters 'vcenter_hostname', 'vcenter_username'
          and 'vcenter_password' in vars/test.yml.
      when: not vcenter_is_defined

    - name: "Setup vSphere Distributed Switch network"
      include_tasks: vds_network_setup.yml
      when: vcenter_is_defined

- name: "Check network environment with either type is setup"
  ansible.builtin.assert:
    that:
      - (vds_network_is_setup is defined and vds_network_is_setup) or (vss_network_is_setup is defined and vss_network_is_setup)
    fail_msg: >-
      Neither the vSphere Distributed Switch network environment nor the vSphere Standard Switch network environment is set up.
