# Copyright 2025 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Setup network environment for testing on ESXi on X86"
  include_tasks: vss_network_setup.yml
  when:
    - esxi_cpu_vendor != 'arm'
    - vss_network_is_setup is undefined or not vss_network_is_setup

- name: "Setup network environment for testing on ESXi on ARM"
  include_tasks: vds_network_setup.yml
  when:
    - esxi_cpu_vendor == 'arm'
    - vds_network_is_setup is undefined or not vds_network_is_setup

# 192.168.192.1 is the static IP address configured on the new added
# network adapter on router VM
- name: "Set fact of the gateway for VM new network adapter"
  ansible.builtin.set_fact:
    new_nic_gateway: "{{ (esxi_cpu_vendor == 'arm') | ternary(vds_vmk_ip_addr, '192.168.192.1') }}"
