# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# This task is used for removing the specified xml elements.
# Parameters:
#   xml_file_path: the path of the xml file
#   xml_item_path_list: the list of elements paths to be removed
#   xml_namespaces_dict: the dict of namespaces in xml file
#
- name: "Remove the specified item in file '{{ xml_file_path }}'"
  community.general.xml:
    path: "{{ xml_file_path }}"
    xpath: "{{ xml_item_path }}"
    state: absent
    namespaces: "{{ xml_namespaces_dict | default(omit) }}"
  with_items: "{{ xml_item_path_list }}"
  loop_control:
    loop_var: xml_item_path
  register: change_xml_result

- name: "Display the xml file change result"
  ansible.builtin.debug: var=change_xml_result
  when: enable_debug
