# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# This task is used for changing the text content of the
# specified xml elements.
# Parameters:
#   xml_file_path: the path of the xml file
#   xml_item_value: the expected value
#   xml_item_path_list: the list of elements paths to be changed
#
- name: "Set value of specified items in file '{{ xml_file_path }}'"
  community.general.xml:
    path: "{{ xml_file_path }}"
    xpath: item
    value: "{{ xml_item_value }}"
  with_items: "{{ xml_item_path_list }}"
  register: change_xml_result

- name: "Display the xml file change result"
  ansible.builtin.debug: var=change_xml_result
  when: enable_debug
