# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# This task is used for changing the text content of the
# specified xml elements.
# Parameters:
#   xml_file_path: the path of the xml file
#   xml_item_value: the expected value
#   xml_item_path_list: the list of items paths to be changed
#   xml_namespaces_dict: the dict of namespaces in xml file
#
- name: "Set value of specified item in file '{{ xml_file_path }}'"
  community.general.xml:
    path: "{{ xml_file_path }}"
    xpath: "{{ xml_item_path }}"
    value: "{{ xml_item_value }}"
    namespaces: "{{ xml_namespaces_dict | default(omit) }}"
  register: change_xml_result
  with_items: "{{ xml_item_path_list }}"
  loop_control:
    loop_var: xml_item_path

- name: "Display the xml file change result"
  ansible.builtin.debug: var=change_xml_result
  when: enable_debug
