# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get vCenter version, build number info by vmware_about_info module
- name: "Initialize vCenter server version and build"
  ansible.builtin.set_fact:
    vcenter_version: 'N/A'
    vcenter_build: 'N/A'

- name: "Get vCenter server version and build info when vCenter server is specified"
  when: vcenter_is_defined is defined and vcenter_is_defined
  block:
    - name: "Get vCenter server about info"
      community.vmware.vmware_about_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: "{{ validate_certs | default(false) }}"
      register: vcenter_about_info
    - name: "Set fact of vCenter version and build number"
      ansible.builtin.set_fact:
        vcenter_version: "{{ vcenter_about_info.about_info.version }}"
        vcenter_build: "{{ vcenter_about_info.about_info.build }}"
      when:
        - vcenter_about_info.about_info is defined
        - vcenter_about_info.about_info.version is defined
        - vcenter_about_info.about_info.build is defined

    - name: "Check vCenter version and build number"
      ansible.builtin.assert:
        that:
          - vcenter_version and vcenter_version != 'N/A'
          - vcenter_build and vcenter_build != 'N/A'
        fail_msg: "Failed to get vCenter version and build from VMware about info: {{ vcenter_about_info.about_info | default('') }}."

# This debug info is for log plugin to get vCenter info
- name: "Print vCenter Server hostname"
  ansible.builtin.debug: var=vcenter_hostname
- name: "Print vCenter Server version"
  ansible.builtin.debug: var=vcenter_version
- name: "Print vCenter Server build"
  ansible.builtin.debug: var=vcenter_build
