# Copyright 2023-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Setup vSphere Distributed Switch (VDS) networking, include:
#   - Create a new vSphere Distributed Switch
#   - Create a new distributed port group
#   - Add ESXi host to the vSphere Distributed Switch
#   - Add a VMkernel network adapter on the ESXi host and assign with distributed port group
#
- name: "Get the vSphere Distributed Switch info on ESXi host"
  include_tasks: esxi_get_vds_info.yml

- name: "Check the number of vSphere Distributed Switch on ESXi host"
  ansible.builtin.assert:
    that:
      - get_host_vds_result.distributed_virtual_switches is defined
      - get_host_vds_result.distributed_virtual_switches | length < 15
    fail_msg: >-
      There are already '{{ get_host_vds_result.distributed_virtual_switches | length }}' vSphere Distributed Switch
      connected by ESXi host '{{ esxi_hostname }}', please remove any unused ones to adhere to the recommended maximum of 16.
      Exceeding this value can lead to unexpected behavior and is generally not a supported configuration.

- name: "Set facts to prepare vSphere Distributed Switch network"
  ansible.builtin.set_fact:
    vds_name: "DSwitch{{ testrun_timestamp }}"
    vds_portgroup_name: "DPortGroup{{ testrun_timestamp }}"
    network_env_net_mask: "255.255.255.0"
    network_env_net_prefix: 24

- name: "Create a new vSphere Distributed Switch '{{ vds_name }}'"
  include_tasks: vcenter_manage_vds.yml
  vars:
    vds_state: "present"

- name: "Create a new distributed port group"
  include_tasks: vcenter_manage_vds_portgroup.yml
  vars:
    vds_portgroup_state: "present"

- name: "Add ESXi host to the vSphere Distributed Switch"
  include_tasks: vcenter_manage_vds_host.yml
  vars:
    vds_host_state: "present"

- name: "Get new VMkernel network adapter device"
  include_tasks: esxi_get_new_vmkernel_adapter.yml

- name: "Set facts of the new VMkernel network adapter index,  name and IP address"
  ansible.builtin.set_fact:
    vds_vmk_device_index: "{{ new_vmk_device_index }}"
    vds_vmk_device_name: "{{ new_vmk_device_name }}"
    vds_vmk_ip_addr: "192.168.{{ new_vmk_device_index | int }}.1"

- name: "Set fact of the network info for the new VMkernel network adapter"
  ansible.builtin.set_fact:
    vds_vmk_network:
      type: 'static'
      ip_address: "{{ vds_vmk_ip_addr }}"
      subnet_mask: "{{ network_env_net_mask }}"
      default_gateway: "{{ vds_vmk_ip_addr }}"

- name: "Add a VMkernel network adapter assigned to the distributed port group for the ESXi host"
  include_tasks: esxi_manage_vmkernel_adapter.yml
  vars:
    vmk_device: "{{ vds_vmk_device_name }}"
    vmk_state: "present"
    vmk_vds_name: "{{ vds_name }}"
    vmk_portgroup_name: "{{ vds_portgroup_name }}"
    vmk_network: "{{ vds_vmk_network }}"
    vmk_enable_mgmt: false

- name: "Check the result of adding new VMkernel network adapter device"
  ansible.builtin.assert:
    that:
      - manage_vmk_result.changed is defined
      - manage_vmk_result.changed
      - manage_vmk_result.device is defined
      - manage_vmk_result.device == vds_vmk_device_name
    fail_msg: >-
      Failed to add new VMkernel network adapter '{{ vds_vmk_device_name }}'.
      The 'changed' value in task result is '{{ manage_vmk_result.changed | default(false) }}'.
      The VMkernel network adapter device name in task result is
      "{{ manage_vmk_result.device | default('') }}".
    success_msg: "VMkernel network adapter '{{ vds_vmk_device_name }}' is added to ESXi host"

- name: "Set facts of vSphere Distributed Switch network"
  ansible.builtin.set_fact:
    vds_network_is_setup: true
    network_env_gateway: "{{ vds_vmk_ip_addr }}"
    network_env_net_name: "{{ vds_portgroup_name }}"
    network_env_nic_ip: "{{ vds_vmk_ip_addr | ansible.utils.ipmath(10) }}"
