# Copyright 2022-2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Add new vTPM device to VM and check device exists.
#
- name: "Add new vTPM device to VM"
  include_tasks: vm_add_remove_vtpm.yml
  vars:
    vtpm_operation: 'present'

- name: "Get vTPM device on VM"
  include_tasks: vm_get_device_with_label.yml
  vars:
    device_label: 'Virtual TPM'

- name: "Check vTPM device exists on VM"
  ansible.builtin.assert:
    that:
      - device_info_with_label is defined
      - device_info_with_label != ""
    fail_msg: "Can not get vTPM device on VM: '{{ device_info_with_label | default('') }}'"
