# Copyright 2021-2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Add a new '{{ adapter_type }}' adapter in '{{ portgroup_name }}' to VM '{{ vm_name }}'"
  community.vmware.vmware_guest_network:
    hostname: "{{ vsphere_host_name }}"
    username: "{{ vsphere_host_user }}"
    password: "{{ vsphere_host_user_password }}"
    validate_certs: "{{ validate_certs | default(False) }}"
    datacenter: "{{ vsphere_host_datacenter }}"
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    network_name: "{{ portgroup_name }}"
    state: present
    device_type: "{{ adapter_type }}"
    connected: true
    start_connected: true
  register: add_adapter

- name: Display the result of adding new network adapter
  ansible.builtin.debug: var=add_adapter
  when: enable_debug is defined and enable_debug
