# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get VM device with the device key
# Parameters:
#   device_key: the device key
# Return:
#   device_info_with_key: the info of device with specified device key
#
- name: "Initialize the device info"
  ansible.builtin.set_fact:
    device_info_with_key: ""

- name: "Get VM hardware device info"
  include_tasks: vm_get_config.yml
  vars:
    property_list: ['config.hardware.device']

- name: "Look for device with key '{{ device_key }}'"
  ansible.builtin.set_fact:
    device_list_with_key: "{{ vm_config.config.hardware.device | selectattr('key', 'equalto', device_key | int) }}"

- name: "Set fact the info of device with key '{{ device_key }}'"
  ansible.builtin.set_fact:
    device_info_with_key: "{{ device_list_with_key[0] }}"
  when: device_list_with_key and device_list_with_key | length > 0

- name: "Print device info"
  ansible.builtin.debug: var=device_info_with_key
