# Copyright 2022-2023 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Initialize the VBS status of VM and VBS status in guest OS"
  ansible.builtin.set_fact:
    vm_vbs_enabled_before: false
    guest_vbs_enabled_before: false

# Get VM VBS status before enable
- include_tasks: ../../common/vm_get_vbs_status.yml
- name: "Set fact of VM VBS current status before enable"
  ansible.builtin.set_fact:
    vm_vbs_enabled_before: "{{ vm_vbs_enabled }}"

- name: "VM VBS is not enabled"
  block:
    # Shutdown guest OS before enabling VBS on VM
    - include_tasks: ../utils/win_shutdown_restart.yml
      vars:
        set_win_power_state: "shutdown"
    # Enable VBS on VM
    - include_tasks: ../utils/win_enable_vbs_vm.yml
      vars:
        win_enable_vbs: true
    - include_tasks: ../../common/vm_set_power_state.yml
      vars:
        vm_power_state_set: "powered-on"
    - include_tasks: ../utils/win_update_inventory.yml
    # Check VM VBS status
    - include_tasks: ../../common/vm_get_vbs_status.yml
    - name: "Check VM VBS status after enable"
      ansible.builtin.assert:
        that:
          - vm_vbs_enabled is defined
          - vm_vbs_enabled | bool
        fail_msg: "VM VBS status is not enabled after enabling it."
  when: not vm_vbs_enabled_before

- name: "Get Device Guard available security properties in guest OS"
  include_tasks: ../utils/win_get_dg_security_properties.yml

- name: "Enable VBS and security services in guest OS"
  include_tasks: ../utils/win_enable_vbs_guest.yml

- name: "Get running security services"
  include_tasks: ../utils/win_get_vbs_guest.yml

# SecurityServicesRunning:
# 0. 	No services running.
# 1. 	If present, Windows Defender Credential Guard is running.
# 2. 	If present, HVCI is running.
# 3. 	If present, System Guard Secure Launch is running.
# 4. 	If present, SMM Firmware Measurement is running.
# VirtualizationBasedSecurityStatus: 2 means VBS is enabled and running
- name: "Check VBS and running security service status"
  ansible.builtin.assert:
    that:
      - win_vbs_status_guest | int == 2
      - "'2' in win_vbs_running_service"
    fail_msg: "VBS is not running '{{ win_vbs_status_guest }}', or HVCI is not running '{{ win_vbs_running_service }}'."
