# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Initialize the memory hot add size list"
  ansible.builtin.set_fact:
    memory_hotadd_size_list: []

- name: "Get ESXi host free memory size"
  include_tasks: ../../common/esxi_get_cpu_mem_info.yml

# Set maximum memory size of this hot add test to the minimum of ESXi
# host free memory size and configured parameter value
# 'vm_memory_hotadd_max'(default 16384) in vars/test.yml
- name: "Generate memory hot add size list when free memory size in host > 4096MB"
  when: esxi_memory_free_mb | int > 4096
  block:
    - name: "Set fact of the maximum VM memory size"
      ansible.builtin.set_fact:
        max_memory_mb: "{{ [esxi_memory_free_mb | int - 4096 + vm_initial_mem_mb | int, vm_memory_hotadd_max | default(16384)] | min }}"
    - name: "Display the maximum memory size set in this testing"
      ansible.builtin.debug: var=max_memory_mb

    # Assume hot added memory size is 1GB, 2GB, 3GB, ...,etc. in this testing,
    # after hot add, VM memory size is less than the value of 'max_memory_mb'.
    # Assume will do N times memory hot add,
    # 1024 * (1 + 2 + 3 + ... + N) = max_memory_mb - vm_initial_mem_mb,
    # set N = root((max_memory_mb - vm_initial_mem_mb) * 2 / 1024) here for convenience.
    - name: "Set fact of the memory hot add size list"
      ansible.builtin.set_fact:
        memory_hotadd_size_list: "{{ range(1024, (((max_memory_mb | int - vm_initial_mem_mb | int) * 2048) | root | int), 1024) | list }}"

- name: "Exit memory hot add test"
  ansible.builtin.debug:
    msg: "Skip VM memory hot add test, the free memory size of ESXi server is lower than 4096MB."
  when: esxi_memory_free_mb | int <= 4096

- name: "Display the under test memory hot add size list"
  ansible.builtin.debug: var=memory_hotadd_size_list
