# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Get VM memory size before memory hotadd
- name: "Get VM guest facts"
  include_tasks: ../../common/vm_get_guest_facts.yml

- name: "Set fact of the memory size before hot add"
  ansible.builtin.set_fact:
    mem_before_hotadd: "{{ vm_guest_facts.instance.hw_memtotal_mb }}"

- name: "Set fact of the memory size after hot add"
  ansible.builtin.set_fact:
    mem_after_hotadd: "{{ (mem_before_hotadd | int) + (hotadd_mb | int) }}"

- name: "Exit memory hot add test"
  ansible.builtin.debug:
    msg: "After hot add {{ hotadd_mb }}MB, VM memory size will be greater than {{ max_memory_mb }}MB. Skip this hot add test."
  when: mem_after_hotadd | int > max_memory_mb | int

- name: "Execute memory hot add test"
  when: mem_after_hotadd | int <= max_memory_mb | int
  block:
    # It requires a cold add when VM memory size is less than
    # 3072MB before hot add, and greater than 3072MB after hot add.
    - name: "Shutdown guest OS when VM memory size <= 3072MB"
      include_tasks: ../utils/shutdown.yml
      when:
        - mem_before_hotadd | int <= 3072
        - mem_after_hotadd | int > 3072
    - name: "Cold add VM memory size from <= 3072MB to > 3072MB"
      include_tasks: ../../common/vm_set_memory_size.yml
      vars:
        memory_mb: "{{ mem_after_hotadd }}"

    - name: "Power on VM after memory cold add situation"
      when:
        - mem_before_hotadd | int <= 3072
        - mem_after_hotadd | int > 3072
      block:
        - name: "Power on VM"
          include_tasks: ../../common/vm_set_power_state.yml
          vars:
            vm_power_state_set: 'powered-on'

        - name: "Refresh in memory host IP info"
          include_tasks: ../../common/update_inventory.yml

    - name: "Check VM connection is not broken after memory hot add"
      block:
        - name: "Pause 5 seconds then check VM connection status"
          ansible.builtin.pause:
            seconds: 5
        - name: ""
          include_tasks: ../../common/vm_wait_connection.yml
          vars:
            vm_wait_connection_timeout: 900
      when: >
        mem_before_hotadd | int > 3072 or
        mem_after_hotadd | int <= 3072

    # Get VM memory size in guest OS
    - include_tasks: ../utils/wait_for_memory_blocks.yml
      vars:
        memory_size_mb: "{{ mem_after_hotadd | int }}"
    - include_tasks: ../utils/memory_size_in_guest.yml

    - name: "Check VM memory size got in guest OS"
      ansible.builtin.assert:
        that:
          - vm_set_mem_size_result | int == memtotal_mb_in_guest | int
        fail_msg: "Hotadd '{{ hotadd_mb }}' MB memory from '{{ mem_before_hotadd }}' MB to '{{ mem_after_hotadd }}' MB, while got '{{ memtotal_mb_in_guest }}' MB in guest OS"
    - name: Set fact of the memory hotadd results
      ansible.builtin.set_fact:
        mem_hotadd_results: "{{ mem_hotadd_results + ['Memory hotadd succeeds: ' ~ mem_before_hotadd ~ '->' ~ mem_after_hotadd] }}"
