# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Set fact of expected Windows online updates categories"
  ansible.builtin.set_fact:
    win_updates_categories_expect:
      - 'Feature Packs'
      - 'Update Rollups'
      - 'Updates'
      - 'Upgrades'
      - 'Windows Insider Pre-Release'
  when:
    - windows_updated_build_num is defined
    - win_os_build_before_update is version(windows_updated_build_num, '<')

- name: "Resume Windows Update in guest OS"
  include_tasks: ../utils/win_pause_resume_win_update.yml
  vars:
    win_update_ops: 'resume'

- name: "Set the reject list of Windows online updates"
  ansible.builtin.set_fact:
    win_updates_reject_list: "{{ windows_updates_reject_list.split(',') | map('trim') }}"
  when:
    - windows_updates_reject_list is defined
    - windows_updates_reject_list

- name: "Search Windows online updates"
  include_tasks: ../utils/win_get_online_updates.yml
  vars:
    win_updates_ignore_errors: "{{ win_updates_categories_expect is undefined }}"

- name: "Install Windows online updates"
  include_tasks: ../utils/win_install_online_updates.yml
  when:
    - win_get_updates_result.found_update_count is defined
    - win_get_updates_result.found_update_count | int != 0
    - win_get_updates_result.updates is defined
    - win_get_updates_result.updates | length != 0

- name: "Skip install Windows online updates"
  ansible.builtin.debug:
    msg: "No updates searched, so will skip Windows online updates install tasks."
  when:
    - win_get_updates_result.updates is defined
    - win_get_updates_result.updates | length == 0
