# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for installing Windows online updates in
# guest OS through Windows Update. If parameter 'windows_updated_build_num'
# is not set, this test case will try to search available Windows online updates
# and install without checking updates categories, updated OS build number.
#
- name: windows_online_updates_install
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Test case block"
      block:
        - name: "Initialize Windows updates install variables"
          ansible.builtin.set_fact:
            win_updates_log_file: "C:\\win_updates_log.txt"
            win_online_updates_installed: false
            win_check_is_updated: false

        - name: "Check parameter 'windows_updated_build_num' value"
          ansible.builtin.assert:
            that:
              - windows_updated_build_num is regex("^[0-9]{5}(\.[0-9]+)?$")
            fail_msg: >-
              Parameter 'windows_updated_build_num' is not set to a valid value: "{{ windows_updated_build_num }}",
              please set it to a valid build number, e.g., '22000', '22000.1', '22000.1234'.
          when:
            - windows_updated_build_num is defined
            - windows_updated_build_num

        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml

        - name: "Get guest OS version build before installing Windows updates"
          include_tasks: ../utils/win_get_os_version.yml
        - name: "Display guest OS version build before installing Windows updates"
          ansible.builtin.debug: var=win_os_version_build
        - name: "Set fact of guest OS build number before installing Windows updates"
          ansible.builtin.set_fact:
            win_os_build_before_update: "{{ ('.').join(win_os_version_build.split('.')[2:]) }}"

        # windows_updated_build_num should be set to the same or newer build num
        # than the current one
        - name: "Check parameter 'windows_updated_build_num' value"
          ansible.builtin.assert:
            that:
              - windows_updated_build_num is version(win_os_build_before_update, '>=')
            fail_msg: >-
              Before installing Windows updates, guest OS build number is '{{ win_os_build_before_update }}',
              which is newer than the configured expected build number '{{ windows_updated_build_num }}',
              please check and change parameter value 'windows_updated_build_num' in vars/test.yml.
          when:
            - windows_updated_build_num is defined
            - windows_updated_build_num

        - name: "Set fact of checking OS build number after installing Windows updates"
          ansible.builtin.set_fact:
            win_check_is_updated: true
          when:
            - windows_updated_build_num is defined
            - windows_updated_build_num
            - windows_updated_build_num is version(win_os_build_before_update, '>')

        - name: "Install Windows online updates in guest OS"
          include_tasks: install_windows_online_updates.yml

        - name: "Windows online updates installed in guest OS"
          include_tasks: post_windows_online_updates.yml
          when: win_online_updates_installed
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
          vars:
            exit_testing_when_fail: true
      always:
        - name: "Check if file {{ win_updates_log_file }} exists in guest OS"
          include_tasks: ../utils/win_check_file_exist.yml
          vars:
            win_check_file_exist_file: "{{ win_updates_log_file }}"
        - name: "Fetch log file {{ win_updates_log_file }} from guest OS"
          include_tasks: ../utils/win_get_file.yml
          vars:
            win_get_file_src_path: "{{ win_updates_log_file }}"
            win_get_file_dst_path: "{{ current_test_log_folder }}"
          when: win_check_file_exist_result
