# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for test Windows VM vCPU hotadd.
# For Windows client: hotadded CPU will not be recognized and used
# after hotadd without OS restart.
# For Windows server: hotadded CPU will be recognized and used after
# hotadd without OS restart.
#
- name: cpu_hot_add_basic
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml

        - name: "Check VM VBS enablement status"
          when: guest_os_ansible_architecture == "64-bit"
          block:
            # Refer to KB article https://knowledge.broadcom.com/external/article?legacyId=52584
            - include_tasks: ../../common/vm_get_vbs_status.yml
            - include_tasks: ../../common/skip_test_case.yml
              vars:
                skip_msg: "Skip test case due to CPU hotadd not supported for VM with VBS enabled."
                skip_reason: "Not Supported"
              when: vm_vbs_enabled

        - name: "Set fact of the initial CPU number to 2"
          ansible.builtin.set_fact:
            initial_cpu_num: 2
        - name: "Set fact of the initial cores per socket"
          ansible.builtin.set_fact:
            initial_cores_num: |-
              {%- if guest_os_product_type == 'server' -%}1
              {%- elif guest_os_product_type == 'client' -%}2
              {%- endif -%}

        - name: "Generate the list of added CPU number for testing"
          include_tasks: ../../linux/cpu_hot_add_basic/generate_cpu_hot_add_list.yml

        - name: "Skip test case when the list of added CPU number is empty"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Test case '{{ ansible_play_name }}' is blocked because vCPU hotadd test value list is empty"
            skip_reason: "Blocked"
          when: cpu_hotadd_num_list | length == 0

        - name: "Initialize the CPU hotadd test result"
          ansible.builtin.set_fact:
            cpu_hotadd_results: []
        - name: "Preparation for CPU hotadd test"
          include_tasks: cpu_hot_add_prepare.yml
          vars:
            enable_vm_cpu_hotadd: true
        - name: "CPU hotadd test on Windows Server"
          include_tasks: cpu_hot_add_validate.yml
          loop: "{{ cpu_hotadd_num_list }}"
          loop_control:
            loop_var: hotadd_num
          when: guest_os_product_type == "server"

        - name: "CPU hotadd test on Windows Client"
          include_tasks: cpu_hot_add_test_client.yml
          when: guest_os_product_type == "client"

        - name: "Display the test results"
          ansible.builtin.debug: var=cpu_hotadd_results
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
