# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for Windows Server VM vCPU hot add testing.
# Notes:
#   For Windows client VM, hot added CPU is not recognized and used in
# guest OS without OS restart after vCPU hot add operation on VM. This
# vCPU hot add feature is displayed "Not supported" in Broadcom Compatibility
# Guide (https://compatibilityguide.broadcom.com/search?program=software&
# persona=live&column=osVendors&order=asc). For testing purpose only, this test
# case uses "devcon.exe" tool to get CPU info in guest OS after vCPU hot adding.
#
- name: cpu_hot_add_basic
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Test case block"
      block:
        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: >-
              Skip test case '{{ ansible_play_name }}' because vCPU hot add is not supported
              on ARM ESXi host.
            skip_reason: "Not Supported"
          when: esxi_cpu_vendor == 'arm'

        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml

        - name: "Check VM VBS enablement status"
          when: guest_os_ansible_architecture == "64-bit"
          block:
            # Refer to KB article https://knowledge.broadcom.com/external/article?legacyId=52584
            - name: "Get VM VBS enablement status"
              include_tasks: ../../common/vm_get_vbs_status.yml
            - name: "Skip test case"
              include_tasks: ../../common/skip_test_case.yml
              vars:
                skip_msg: >-
                  Skip test case '{{ ansible_play_name }}' because vCPU hot add is not supported
                  for VM with VBS enabled.
                skip_reason: "Not Supported"
              when: vm_vbs_enabled

        - name: "Set fact of the initial CPU number to 2"
          ansible.builtin.set_fact:
            initial_cpu_num: 2
        - name: "Set fact of the initial cores per socket"
          ansible.builtin.set_fact:
            initial_cores_num: |-
              {%- if guest_os_product_type == 'server' -%}1
              {%- elif guest_os_product_type == 'client' -%}2
              {%- endif -%}

        - name: "Generate hot added CPU number list for Windows Server"
          include_tasks: ../../linux/cpu_hot_add_basic/generate_cpu_hot_add_list.yml
          when: guest_os_product_type == "server"

        - name: "Generate hot added CPU number list for Windows Client"
          include_tasks: cpu_hot_add_win_client.yml
          when: guest_os_product_type == "client"

        - name: "Skip test case"
          include_tasks: ../../common/skip_test_case.yml
          vars:
            skip_msg: "Test case '{{ ansible_play_name }}' is blocked because hot added CPU number list for testing is empty."
            skip_reason: "Blocked"
          when: cpu_hotadd_num_list | length == 0

        - name: "Initialize VM vCPU hot add test result"
          ansible.builtin.set_fact:
            cpu_hotadd_results: []

        - name: "Prepare for VM vCPU hot add test"
          include_tasks: cpu_hot_add_prepare.yml
          vars:
            enable_vm_cpu_hotadd: true

        - name: "VM vCPU hot add test on generated hot added CPU number list"
          include_tasks: cpu_hot_add_validate.yml
          loop: "{{ cpu_hotadd_num_list }}"
          loop_control:
            loop_var: hotadd_num

        - name: "Display the VM vCPU hot add test result"
          ansible.builtin.debug: var=cpu_hotadd_results
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
