# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Display the hot added CPU number"
  ansible.builtin.debug: var=hotadd_num

- name: "Get VM facts"
  include_tasks: ../../common/vm_get_guest_facts.yml

- name: "Set fact of vCPU number before hot add"
  ansible.builtin.set_fact:
    vcpu_before_hotadd: "{{ vm_guest_facts.instance.hw_processor_count }}"

- name: "Set fact of hot add CPU number"
  ansible.builtin.set_fact:
    vcpu_after_hotadd: "{{ vcpu_before_hotadd | int + hotadd_num | int }}"

- name: "Target CPU number is larger than the maximum number"
  ansible.builtin.debug:
    msg: "Hotadd '{{ hotadd_num }}', VM vCPU number is '{{ vcpu_after_hotadd }}', greater than '{{ max_num_cpus }}', skip hot add test"
  when: vcpu_after_hotadd | int > max_num_cpus | int

- name: "Target CPU number not exceed the maximum number"
  when: vcpu_after_hotadd | int <= max_num_cpus | int
  block:
    - name: "Change VM vCPU number"
      include_tasks: ../../common/vm_set_cpu_number.yml
      vars:
        num_cpus: "{{ vcpu_after_hotadd }}"
        num_cores_per_socket: "{{ initial_cores_num }}"

    - name: "Check Windows VM winrm connection"
      include_tasks: ../utils/win_check_winrm.yml

    - name: "Use devcon to detect CPU in Windows Client"
      when: guest_os_product_type == "client"
      block:
        - name: "Get CPU number in guest OS using devcon"
          include_tasks: ../utils/win_get_physical_cpu_devcon.yml
          vars:
            target_guest_os_bitness: "{{ guest_os_ansible_architecture }}"
        - name: "Set fact of the CPU detected by devcon"
          ansible.builtin.set_fact:
            win_cpu_number: "{{ processor_number_devcon }}"

    - name: "Get CPU number in Windows Server directly" 
      include_tasks: ../utils/win_get_cpu_cores_sockets.yml
      when: guest_os_product_type == "server"

    # Validate CPU number after hot add
    - name: "Verify hot added vCPU can be detected in guest OS"
      ansible.builtin.assert:
        that:
          - win_cpu_number | int == vcpu_after_hotadd | int
          - vm_set_cpu_number_result | int == win_cpu_number | int
        fail_msg: "Hotadd vCPU ({{ vcpu_before_hotadd }}->{{ vcpu_after_hotadd }}) failed"

    - name: "Add test result"
      ansible.builtin.set_fact:
        cpu_hotadd_results: "{{ cpu_hotadd_results + ['vCPU hot add succeeds: ' ~ vcpu_before_hotadd ~ '->' ~ vcpu_after_hotadd] }}"
