# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# On ESXi version < 7.0.2, Windows 10 VM max socket is 2,
# on ESXi version >= 7.0.2, Windows 10 VM max socket is 4
- name: "Set fact of the hot add CPU test list"
  ansible.builtin.set_fact:
    cpu_hotadd_num_list: ["{{ initial_cores_num }}"]

- name: "Set fact of the hot add CPU test list"
  ansible.builtin.set_fact:
    cpu_hotadd_num_list: ["{{ cpu_hotadd_num_list * 3 }}"]
  when: esxi_version is version('7.0.2', '>=')

- name: "Print the CPU hot add value list"
  ansible.builtin.debug:
    msg: "Hot add CPU test value list for Windows client: {{ cpu_hotadd_num_list | to_yaml }}"

- name: "Execute VM CPU hot add and verify test"
  include_tasks: cpu_hot_add_validate.yml
  loop: "{{ cpu_hotadd_num_list }}"
  loop_control:
    loop_var: hotadd_num
