# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Set the reject list of Windows online updates"
  ansible.builtin.set_fact:
    win_updates_reject_list: "{{ windows_updates_reject_list.split(',') | map('trim') }}"
  when:
    - windows_updates_reject_list is defined
    - windows_updates_reject_list

- name: "Install Windows online updates"
  include_tasks: ../utils/win_install_online_updates.yml

- name: "Check if Windows online updates install log file exists in guest OS"
  include_tasks: ../utils/win_check_file_exist.yml
  vars:
    win_check_file_exist_file: "{{ win_updates_log_file }}"

- name: "Fetch the log file of Windows online updates installation"
  include_tasks: ../utils/win_get_file.yml
  vars:
    win_get_file_src_path: "{{ win_updates_log_file }}"
    win_get_file_dst_path: "{{ current_test_log_folder }}"
  when: win_check_file_exist_result
