# Copyright 2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
# Description:
#   This test case is used for installing Windows online updates in
# guest OS through Windows Update.
#
- name: windows_online_update
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Test case block"
      block:
        - name: "Check parameter 'windows_updated_build_num' value"
          ansible.builtin.assert:
            that:
              - windows_updated_build_num is regex("^[0-9]{5}(\.[0-9]+)?$")
            fail_msg: >-
              Parameter 'windows_updated_build_num' is not set to a valid value: "{{ windows_updated_build_num }}",
              please set it to a valid build number, e.g., '22000', '22000.1', '22000.1234'.
          when: windows_updated_build_num is defined

        - name: "Test setup"
          include_tasks: ../setup/test_setup.yml

        - name: "Get guest OS version build before installing Windows updates"
          include_tasks: ../utils/win_get_os_version.yml
        - name: "Display guest OS version build before installing Windows updates"
          ansible.builtin.debug: var=win_os_version_build

        - name: "Install online updates in guest OS"
          include_tasks: install_online_updates.yml

        - name: "Get guest OS version build after installing Windows updates"
          include_tasks: ../utils/win_get_os_version.yml
        - name: "Display guest OS version build after installing Windows updates"
          ansible.builtin.debug: var=win_os_version_build

        - name: "Check OS build number after installing Windows updates"
          ansible.builtin.assert:
            that:
              - '.'.join(win_os_version_build.split('.')[2:]) is version(windows_updated_build_num, '>=')
            fail_msg: >-
              After installing Windows updates guest OS build number is "{{ '.'.join(win_os_version_build.split('.')[2:]) }}",
              which is not newer than the expected build '{{ windows_updated_build_num }}'.
          when: windows_updated_build_num is defined

        - name: "Remove Windows.old folder after installing Windows updates"
          include_tasks: remove_windows_old.yml

        - name: "Reset base snapshot after installing Windows updates"
          include_tasks: ../../common/reset_base_snapshot.yml
          vars:
            remove_old_base_snapshot: true
            base_snapshot_description: "{{ win_os_version_build }}"
      rescue:
        - name: "Test case failure"
          include_tasks: ../../common/test_rescue.yml
          vars:
            exit_testing_when_fail: true
