# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause
---
- name: "Get VM power status"
  include_tasks: ../../common/vm_get_power_state.yml
- name: "Shutdown guest OS"
  include_tasks: ../utils/shutdown_vm.yml
  when: vm_power_state_get != "poweredOff"

# Set vCPU to specified value, set initial memory
- name: "Set VM memory size to the initial value"
  include_tasks: ../../common/vm_set_memory_size.yml
  vars:
    memory_mb: "{{ vm_initial_mem_mb }}"
- name: "Set VM vCPU number"
  include_tasks: ../../common/vm_set_cpu_number.yml
  vars:
    num_cpus: "{{ vcpu_number }}"
    num_cores_per_socket: "{{ vcpu_number }}"

- name: "Power on VM"
  include_tasks: ../../common/vm_set_power_state.yml
  vars:
    vm_power_state_set: "powered-on"
- name: "Refresh in memory host IP"
  include_tasks: ../utils/win_update_inventory.yml

# Check CPU number in guest OS before memory hot add
- name: "Get CPU info in guest OS"
  include_tasks: ../utils/win_get_cpu_cores_sockets.yml
- name: "Check initial CPU number got from guest OS"
  ansible.builtin.assert:
    that:
      - win_cpu_number | int == vcpu_number | int
    success_msg: "Get CPU number in guest is same as configured CPU: {{ vcpu_number | int }}"
    fail_msg: "Get CPU number in guest: {{ win_cpu_number | int }}, not same as configured CPU: {{ vcpu_number | int }}"

# Check memory size in guest OS before hot add
- name: "Get memory info in guest OS"
  include_tasks: ../utils/win_get_mem_size.yml
- name: "Check initial memory size got from guest OS"
  ansible.builtin.assert:
    that:
      - vm_initial_mem_mb | int == win_get_mem_size | int
    success_msg: "Get memory size in guest is same as initial memory: {{ win_get_mem_size | int }}MB"
    fail_msg: "Get memory size in guest: {{ win_get_mem_size | int }}MB, not same as initial memory set: {{ vm_initial_mem_mb }}MB"

- name: "Execute memory hot add test"
  include_tasks: hotadd_memory_verify.yml
  loop: "{{ memory_hotadd_size_list }}"
  loop_control:
    loop_var: hotadd_mb
